### ISSUE TITLE
View controllers' views added only when segment clicked

### ISSUE THREAD

**Issue by stefanocdn** [maxep/MXSegmentedPager#1]
Hi, is there an easy way to use

```
- (UIView *)segmentedPager:(MXSegmentedPager *)segmentedPager viewForPageAtIndex:(NSInteger)index
```

to use View Controller Subviews that would be loaded only when the corresponding segment control is selected?

The goal would be to use view controllers' subviews where data is loaded.

**Comment by maxep** [comment]
Hi,

If you want to dynamically set the content of a page every time the segment control is pressed, you can use the delegate method `segmentedPager:didSelectView` to load the content of the specific page.

For exemple, set an empty view when data are loaded and then set the content in the delegate method :

```
- (UIView *)segmentedPager:(MXSegmentedPager *)segmentedPager viewForPageAtIndex:(NSInteger)index {
    //Set you initial view
}

- (void) segmentedPager:(MXSegmentedPager*)segmentedPager didSelectView:(UIView*)view {
    //Dynamically set the content of view
}
```
