### ISSUE TITLE
Header Imageview gets 'stuck' at larger size when pulled down in parallax mode

### ISSUE THREAD

**Issue by inPhilly** [maxep/MXSegmentedPager#10]
When I use MXSegmentedPager for my detail controller in a uisplitviewcontroller, I encounter the following issue.

Pulling down the view past a certain point results in the enlarged image view 'sticking' at its enlarged size. When the view is released and the header returns to normal size, the imageview is still enlarged.

This is happening in the split view sample app we looked at in a previous issue.

**Comment by maxep** [comment]
Hi @mommyme !

Sorry for the late response. I guess I had a wrong approach on the parallax header category.
It was not flexible and accurate. I have been working on a new solution which is a bit more complex but I like the result. Could you please have a look and open issues if you have any regressions? If it fixes your current open bugs, please close it.

PS: it is not ios7 friendly for now!

Regards,

Maxime

**Comment by inPhilly** [comment]
This seems to have been fixed by the latest release. I will let you know if any different, but thanks again for this great control - which is now even better!
