### ISSUE TITLE
trigger lifecycle methods on paged viewcontrollers

### ISSUE THREAD

**Issue by idokleinman** [maxep/MXSegmentedPager#103]
I want viewWillAppear/Disappear to trigger whenever user switches to relevant segment view - how can I achieve that? 

introducing MXSegementedPager to my app caused lots of breakage with good existing code...

**Comment by maxep** [comment]
Pages are child view controller, `viewWillAppear`/`viewWillDisappear` are triggered when the are added/removed from the parent, not on every user switch.
You can subclass MXSegmentedPagerController and trigger these methods manually.
