### ISSUE TITLE
All buttons under child viewcontrollers for pager views lose their "blink" animation when touched

### ISSUE THREAD

**Issue by idokleinman** [maxep/MXSegmentedPager#104]
All UIButtons of the viewcontrollers that get selected in MXSegmentedPager lost their "blink" animation when touched.

Any idea why or how to fix it?

**Comment by maxep** [comment]
There blink? are you sure its related to MXSegmentedPager, it's just a container.

**Comment by idokleinman** [comment]
They were blinking fine on the VCs under the pager before I integrated it...
