### ISSUE TITLE
Pager hide behind navigation bar

### ISSUE THREAD

**Issue by ompagi** [maxep/MXSegmentedPager#108]
there is this MXSegmentedPager integrated viewcontroller that was pushed from a button click(push segue) with no header and the problem is the segmented pager is hiding behind the navigation bar. I have to set an empty header with the exact height so that the segmented pager is exactly below the navigation bar.

**Comment by ompagi** [comment]
and adding an empty header with a specific height cut off some of table view segment page bottom offset , resulting me to unable to scroll to the bottom cell

**Comment by maxep** [comment]
In your storyboard, you can try to uncheck the `Under Top Bars` in the Extend Edges of you view controller.

**Comment by ompagi** [comment]
That kinda solve the problem of making the pager visible, but it is still overlapping the navigation bar. nevertheless, it's safe to close this issue now, thank you.
