### ISSUE TITLE
parallaxHeaderview from view in storyboard ? 

### ISSUE THREAD

**Issue by myusuf08** [maxep/MXSegmentedPager#110]
parallaxHeaderview from view in storyboard , its possible?

**Comment by maxep** [comment]
Yes, please refer to the examples

**Comment by myusuf08** [comment]
but how? please give me a example

**Comment by maxep** [comment]
See exemples in [MXParallaxHeader](https://github.com/maxep/MXParallaxHeader)

**Comment by myusuf08** [comment]
its from xib , not storyboard
