### ISSUE TITLE
How do i use header view with view controller and not xib file?? its possible?

### ISSUE THREAD

**Issue by edisonlin31** [maxep/MXSegmentedPager#113]
Hi @maxep 
iam trying to integrated your library  , how do to use view controller in header view?? , 
its possible? , can you give me a example , because in your project is using xib

**Comment by bksasuke** [comment]
In my case, i create a uiview with xib file, then add it to pager as sample. I haven't try with view controller, but the code in implement file work so i come up with this way.

**Comment by maxep** [comment]
For now you cant add directly a view controller as header. But you can create a floating view in storyboard and add it to the parallax header. Check examples in [MXParallaxHeader](https://github.com/maxep/MXParallaxHeader)
