### ISSUE TITLE
Title not shown when build with iOS 10.0

### ISSUE THREAD

**Issue by JohannesNevels** [maxep/MXSegmentedPager#114]
Currently building with MXSegmentedPager 3.1.0 and iOS10.0 with Xcode Version 8.0 beta 6.
When title length is smaller than 6 chars, it won't be shown. 
We fixed it to extend the string with spaces until 6 chars reached.
This is obviously not **the** fix.
Is this something you could fix in the near future? Or maybe it's an issue in iOS10.0 it self.

**Comment by rutger1337** [comment]
Seems like a bug in the `HMSegmentedControl` dependency. They fixed it in their swift version and closed the issue...

https://github.com/HeshamMegid/HMSegmentedControl/issues/203

**Comment by acubillo** [comment]
There is a new update for Obj-C HMSegmentedControl that seems fixed for this issue. Can you update the dependency to add that fix and see if this solves the issue? 

Best regards,
