### ISSUE TITLE
Constraint not satisfied

### ISSUE THREAD

**Issue by ompagi** [maxep/MXSegmentedPager#117]
My design is as follow : 
![simulator screen shot 7 sep 2016 4 21 21 pm](https://cloud.githubusercontent.com/assets/21188799/18306691/2937add2-7517-11e6-8195-2a6d85ef341a.png)
I've set the height constraint for the bottom forgot your password button and login now button, but not the table view in the middle ( which i shouldn't) . The constraint is fine if i run the app without the pager ( with the navigation bar) , but the constraint isn't satisfied when i run the app with the pager. It looks fine to me, but i'd prefer no constraint problem showing in my xcode. Any help?

p.s. : I tried to delete the table view and only keep both buttons, but it still fails.

**Comment by maxep** [comment]
Fixed in #121
