### ISSUE TITLE
UITableView stuck scrolling (first touch missing)

### ISSUE THREAD

**Issue by apascual** [maxep/MXSegmentedPager#122]
Basically, when you scroll to top, sometimes the UITableView gets somehow stuck (on the simulator the scroll indicator remains present forever). The biggest issue is that the UITableView will capture that tap and so if you tap on a cell, nothing will happen the first time.

![ezgif-1935674841](https://cloud.githubusercontent.com/assets/3491658/19509629/f535725a-95df-11e6-85dc-486b5a58d0dc.gif)

**Comment by Ezimetjan** [comment]
Did you solve this problem?  I am experiencing the same issue with ParallaxHeader. Sometimes first touch is ignored after bouncing the ParallaxHeader.

**Comment by apascual** [comment]
@Ezimetzhan No, sorry, I didn't have time to research it in depth... It looks that for some reason the TableView keeps indeterminately the "scrolling-status" and that is why the first touch is ignored. Have a look to the scrollbar on the right.

Good luck!
