### ISSUE TITLE
NSInternalInconsistencyException with pager from storyboard 

### ISSUE THREAD

**Issue by CompassCanJV** [maxep/MXSegmentedPager#124]
I've tried getting the MXSegmentPager working from the storyboard, and while I managed to get it working on your MXSimpleViewController example, it keeps crashing for me in my own code.

This is the message I get:
    `*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Number of pages in MXSegmentedPager must be greater than 0'`

Here is what I changed on your example.

```
 `@interface MXSimpleViewController () <MXSegmentedPagerDelegate, MXSegmentedPagerDataSource, UITableViewDelegate, UITableViewDataSource>

@property (weak, nonatomic) IBOutlet MXSegmentedPager *segmentedPager;

//@property (nonatomic, strong) MXSegmentedPager  * segmentedPager;
@property (nonatomic, strong) UITableView       * tableView;
@property (nonatomic, strong) UIWebView         * webView;
@property (nonatomic, strong) UITextView        * textView;
@end

@implementation MXSimpleViewController

- (void)viewDidLoad {
[super viewDidLoad];
self.view.backgroundColor = [UIColor greenColor];


self.segmentedPager.delegate    = self;
self.segmentedPager.dataSource  = self;

[self.view addSubview:self.segmentedPager];
self.segmentedPager.segmentedControl.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationDown;
self.segmentedPager.segmentedControl.selectionIndicatorColor = [UIColor orangeColor];
self.segmentedPager.segmentedControl.selectionStyle = HMSegmentedControlSelectionStyleFullWidthStripe;
self.segmentedPager.segmentedControl.selectedTitleTextAttributes = @{NSForegroundColorAttributeName : [UIColor orangeColor]};

self.segmentedPager.pager.gutterWidth = 20;

    //Register UItableView as page
    [self.segmentedPager.pager registerClass:[UITextView class] forPageReuseIdentifier:@"TextPage"];
}`
```

and commented-out this property method:

```
 `/*
- (MXSegmentedPager *)segmentedPager {
if (!_segmentedPager) {

    // Set a segmented pager
    _segmentedPager = [[MXSegmentedPager alloc] init];
    _segmentedPager.delegate    = self;
    _segmentedPager.dataSource  = self;
}
return _segmentedPager;
 }*/`
```

Is there anything I am missing to successfully get the MXSegmentPager working from the storyboard?

**Comment by maxep** [comment]
Are you using the `MXSegmentedPagerController`? in that case, how did you configure your segues identifiers?
If you embed a MXSegmentedPager in your own VC, how did you implement the `MXSegmentedPagerDataSource`?

**Comment by CompassCanJV** [comment]
Just as you see above

`@interface MXSimpleViewController () <MXSegmentedPagerDelegate, MXSegmentedPagerDataSource, UITableViewDelegate, UITableViewDataSource>
`
But with my own class. I wanted to make it the datasource for the segmentPager and I have these methods implemented:

```
- (NSInteger)numberOfPagesInSegmentedPager:(MXSegmentedPager *)segmentedPager{

    return MAX(array.count,1);
}

- (NSString *)segmentedPager:(MXSegmentedPager *)segmentedPager titleForSectionAtIndex:(NSInteger)index{

    return @"string";
}

- (UIView *)segmentedPager:(MXSegmentedPager *)segmentedPager viewForPageAtIndex:(NSInteger)index{

    UITableView *tableCopy = [self.tableView copy];
    tableCopy.tag = index;
    [tableCopy reloadData];

    return tableCopy;
}
```

**Comment by maxep** [comment]
ok I see, its a bug.. It tries to load the pages but the datasource is not yet assigned!
You can try to set the datasource/delegate directly from storyboard, not in the `viewDidLoad`

**Comment by CompassCanJV** [comment]
How do I try that? Would I make an IBOutlet for `MXSegmentedPagerDelegate` and `MXSegmentedPagerDataSource` and then link them to the storyboard?

What if I overwrite my VC's init method?

**Comment by CompassCanJV** [comment]
It just occurred to me that the MXSimpleViewController you've implemented is reached with a custom segue. My VC is reached with a generic show segue, could there be an issue with how that is set up in the storyboard?

**Comment by maxep** [comment]
No it is not related, the MXSimpleViewController is just embed in a MXSegmentedPagerController for the example :)

**Comment by CompassCanJV** [comment]
Here is what I did to make the storyboard implementation work in your MXSimpleViewController. it's a rather simple change, so I don't understand why the same implementation wont work in my own project. All i did from the storyboard is set a UIView into MXSimple and change it to an MXSegmentPager before linking it to the IBOutlet.

[MXSimple Mods.txt](https://github.com/maxep/MXSegmentedPager/files/553533/MXSimple.Mods.txt)

**Comment by maxep** [comment]
Its not the same implementation since you instantiate the segmented pager from storyboard. It will try to load the pages before reaching the `viewDidLoad`. By setting the delegate and datasource directly from storyboard, you might workaround this bug.

**Comment by CompassCanJV** [comment]
I thought I was instantiating the segmentPager from the storyboard with my modded MXSimpleViewController; as you see the IBOutlet in the class. How do I link the delegate and datasource from the storyboard? I can't seem to do it like I would with a UITableView.

**Comment by maxep** [comment]
Yes your are instantiating the segmented pager from storyboard. Actually I didnt add the `@IBOultet` to delegate/datasource, so you cant.. I will add it!

**Comment by CompassCanJV** [comment]
Awesome, thanks! lol
