### ISSUE TITLE
Coming back from pushed controller, changes the header's size

### ISSUE THREAD

**Issue by HarshitDaftary** [maxep/MXSegmentedPager#127]
If I push the controller and come back, it reduces the header's size by 20 px (probably same as status bar). But If I present controller and come back, it works fine and keeps the header's size same as it was previously.

![graphics interchange format gif -0caae24a0cfe-1](https://cloud.githubusercontent.com/assets/2654829/19947286/63ed239e-a16d-11e6-9496-2d05df0dd8c8.gif)

**Comment by mucahittekin** [comment]
I think you have to set automaticallyAdjustsScrollViewInsets to false in your view controller
