### ISSUE TITLE
Set tintColor of images

### ISSUE THREAD

**Issue by fishfisher** [maxep/MXSegmentedPager#129]
First off all, thanks for this great library. Love it.
Is it possible to set the tint of the images used when HMSegmentedControlType is set to .images or .textImages?

**Comment by maxep** [comment]
Thanks and sorry for the late response. I think you should look at the `titleTextAttributes` of [`HMSegmentedControl`](http://cocoadocs.org/docsets/HMSegmentedControl/1.5.3/Classes/HMSegmentedControl.html), but I dont think you can set a tint color to the segment images..
