### ISSUE TITLE
Hide the title bar

### ISSUE THREAD

**Issue by mohdumarj** [maxep/MXSegmentedPager#131]
how  can we hide the title bar in case if we are showing only on view in body? I want to disable the tiltle bar or make its height 0, or something that will make it disappear. 
how can i do that?

**Comment by sin2** [comment]
```
- (CGFloat)heightForSegmentedControlInSegmentedPager:(MXSegmentedPager *)segmentedPager {
     return 44.0f;
}
```
You can use that delegate method
