### ISSUE TITLE
Problem on Programatic use Swift3 

### ISSUE THREAD

**Issue by dipkasyap** [maxep/MXSegmentedPager#133]
The delegate method **only being called for 2 times**, not according to the **numberOfPages** supplied 
but   titleForSectionAt is being called according to the **numberOfPages** supplied 

 **override func segmentedPager(_ segmentedPager: MXSegmentedPager, viewControllerForPageAt index: Int) -> UIViewController**

**INfo** - This problem is only on programatic use , when i used with the storyboard and segues it is fine, i tried to debug, no luck !

**Comment by dipkasyap** [comment]
Actually there was some

**Comment by dipkasyap** [comment]
There was confusion with cache of VC , it only caches 2 VC at a time, i debugged for almost 5 hours and found out this silly conclusion ,
**There is no issue with programatic use on Swift 3**

**Comment by sabarics** [comment]
How to handle one VC at a time, because 2nd VC will execute based on 1st VC.
Now 2 VC is runs at a time. Any solution please.
