### ISSUE TITLE
setSelectedSegmentIndex didn't work

### ISSUE THREAD

**Issue by bungkhus** [maxep/MXSegmentedPager#135]
Hi,
I tried it when the application is run directly to a specific tab. I use this `self.segmentedPager.segmentedControl.setSelectedSegmentIndex (1, animated: false)` but this did not work.

**Comment by danialmoghaddam** [comment]
+1

**Comment by chengsokneng** [comment]
+1

**Comment by chengsokneng** [comment]
i try to use this one and it work:
self.segmentedPager.pager.showPage(at: index, animated: true)

**Comment by bungkhus** [comment]
@chengsokneng thanks dude 👍

**Comment by KushThakkar** [comment]
@chengsokneng 
Its doesn't work for me.

Any one Help.

**Comment by hippier007** [comment]
self.segmentedPager.pager.showPage(at: index, animated: true). It works for me.

**Comment by YaroslavNedoluga** [comment]
Try to move this self.segmentedPager.pager.showPage(at: index, animated: true) in viewDidAppear for example.
