### ISSUE TITLE
Parallax Header Offset returns wrong values when scrolling fast

### ISSUE THREAD

**Issue by DrJid** [maxep/MXSegmentedPager#136]
In the method ` segmentedPager:didScrollWithParallaxHeader:` the value of `parallaxHeader.progress` seems to be wrong when scrolling really quickly. 

In the Swift Example, notice how when I scroll down fast, it sends offset values above 0.0..
Ideally, it should just stay at 0.0 since the size of the header never changed.. 
https://cl.ly/3t47092F0T3S

May or may not be helpful, but in MXParallaxHeader.m#118, If I change `self.contentView` to `self.view`, that seems to resolve it, but I'm not sure what other side effects arise as a result of that.

**Comment by maxep** [comment]
This issue is related to MXParallaxHeader.

**Comment by qasimmajeed** [comment]
Hi @DrJid  did the issue is resolved ? i am also facing the same issue
