### ISSUE TITLE
navigationBar dissapears

### ISSUE THREAD

**Issue by goktugaral** [maxep/MXSegmentedPager#137]
Hi,

I'm using dataSource methods for setup. I'm keeping three viewControllers in controllersArray and I'm using **viewControllerForPageAt** method to show pager. Because some of this viewController has tableView and I want to make user move other viewController too. If I use **viewForPageAtIndex** viewControllers are not clickable so that's not suitable for me. 

I have ProfileVC which is extend from MXSegmentedPagerController. ProfileVC has storyboard with root of some navigationController. The tricky part is navigationBar. When ProfileVC first showed up navigationBar is still there but If I select pager or make push to another viewController is going to disappear 

Do you know what might be the problem is? How I can keep navigationBar, give me some advice please?

//MARK: - SegmentedPager
    
    override func numberOfPages(in segmentedPager: MXSegmentedPager) -> Int {
        return 3
    }
    
    override func segmentedPager(_ segmentedPager: MXSegmentedPager, titleForSectionAt index: Int) -> String {
        return ["A", "B", "C"][index];
    }
    
    override func segmentedPager(_ segmentedPager: MXSegmentedPager, viewControllerForPageAt index: Int) -> UIViewController {
        
        return controllersArray[index] as! UIViewController
    }

**Comment by danialmoghaddam** [comment]
+1
