### ISSUE TITLE
Reference to NavigationController gone in v3.2.1

### ISSUE THREAD

**Issue by fishfisher** [maxep/MXSegmentedPager#139]
What specific changes has been made in the release of v 3.2.1?
In the 3.2.1-release the reference to the NavigationController is nil. Also, if pushing viewcontroller from within MXSegmentedPager the layout of the controller is messed up.

Downgraded to 3.2.0 and the problem is gone.

Anyone else experiencing this?

**Comment by maxep** [comment]
Oups my fault... I've updated MXPageSegue and I forget to apply changes! 
I will push a fix asap

**Comment by fishfisher** [comment]
Thanks for the quick reply! And thanks for the great work!

**Comment by archansel** [comment]
Is it on the latest release? I'm using MXSegmentedPager 3.2.1, MXPagerView (~> 0.1.4)
