### ISSUE TITLE
How can I add a view below the segmentedControl?

### ISSUE THREAD

**Issue by goktugaral** [maxep/MXSegmentedPager#143]
Hi, I want to add a view under the segmentedControl area. Could it be possible?
Thank you

**Comment by jwardle** [comment]
Also interested in this. With the latest version the previous approach of adding a SubView to the Pager view no longer works - the added view appears to stick to one of the pages, whilst before it was clearly attached to the segmented control & remained in position across page scrolls.

**Comment by hardikamal** [comment]
@goktugaral @jwardle Were you able to find solution for this?

**Comment by hardikamal** [comment]
@maxep can you plz help me with this?

**Comment by Evyasafmordechai** [comment]
Just add the subview dynamic in code.
*prefer to add in -viewWillAppear:
