### ISSUE TITLE
Pull to Refresh Bumps

### ISSUE THREAD

**Issue by CavalcanteLeo** [maxep/MXSegmentedPager#144]
I have implemented [INSPullToRefresh](https://github.com/inspace-io/INSPullToRefresh)

To use this, i have set the header mode as `MXParallaxHeaderModeBottom`

```objective-c
self.segmentedPager.parallaxHeader.view = self.headerView;
self.segmentedPager.parallaxHeader.mode = MXParallaxHeaderModeBottom;
self.segmentedPager.parallaxHeader.height = CGRectGetHeight(headerBoxView.bounds);
self.segmentedPager.parallaxHeader.minimumHeight = 0;
```

so, i can now swipe the content with the header down
But I'm facing an issue like in this video, where the header bumps when the `INSPullToRefresh` calls the method pull to refresh 

Video:
http://quick.as/0vzouvpbm

**Comment by maxep** [comment]
It is a strange behavior indeed.. Have you track the MXScrollView's content insets?
You can try to add the progress to the header and animate it with header's progress.
