### ISSUE TITLE
remove parallel effect

### ISSUE THREAD

**Issue by ajaysinghthakur** [maxep/MXSegmentedPager#145]
i want to remove parallex effect on header while scrolling down it should behave like tableview header, Any help would be appreciated.

**Comment by ajaysinghthakur** [comment]
i found it 
self.segmentedPager.bounces = false
sorry for inconvience

**Comment by Govindrgmobiles** [comment]
@ajaysinghthakur Thanks for the question and solution.

**Comment by Sob7y** [comment]
@ajaysinghthakur Thanks for the question and solution.
