### ISSUE TITLE
segmentedPager:didSelectViewWithIndex trigger tab select even if it's already selected

### ISSUE THREAD

**Issue by archansel** [maxep/MXSegmentedPager#146]
Hi,

I have a case in my current implementation which is triggering `segmentedPager:didSelectViewWithIndex` even if the page already selected. For example, I have three pages, current selected index is 1 (the second tab), when I click tab title once again (the second tab), I want to trigger `segmentedPager:didSelectViewWithIndex`, how do I achieve this? thanks

**Comment by maxep** [comment]
Hi @archansel, You can add a target to the segmented control to get the segment selection.
