### ISSUE TITLE
Two view controller execute at same time. How can I handle to execute as single viewcontroller.

### ISSUE THREAD

**Issue by sabarics** [maxep/MXSegmentedPager#150]

**Comment by JyotiNS** [comment]
same issue, I have more than 5 view controllers but randomly any view controller is in the memory rather than selected segment and delegate methods called several times.

**Comment by risechen** [comment]
same issue,how to it with view contollers,not views.No one want to write too many page in one view controller

**Comment by JyotiNS** [comment]
@risechen I have fixed it by keeping index in viewcontroller's property and then when segmented pager calls datasource method set that index to view controller's index.

**Comment by swaroopgs** [comment]
@JyotiNS Can you share that piece of code. It will be of great help!

**Comment by JyotiNS** [comment]
- (UIViewController *)segmentedPager:(MXSegmentedPager *)segmentedPager viewControllerForPageAtIndex:(NSInteger)index {
    
   // NSLog(@"I am here at section : %d",index);
    selectedController = [_controllersMA objectAtIndex:index];
  //here PASS THE DATA required for specific controller. or set the data when you add controller to controllers Array
    selectedController.selectedRoomType = self.Type;
    selectedController.Id = self.roomId;
    return selectedController;
}

//note: _controllersMA contains multiple controllers
//this delegate method is called when segment is changed

//change code in MXSegmentedPagerController.m file
- (UIView *)segmentedPager:(MXSegmentedPager *)segmentedPager viewForPageAtIndex:(NSInteger)index {
    
   SomeViewController *viewController = (SomeViewController *)[self segmentedPager:segmentedPager viewControllerForPageAtIndex:index];
    
    if (viewController) {
        [self addChildViewController:viewController];
        [viewController didMoveToParentViewController:self];
        viewController.currentSectionIndex = (int)index;
        return viewController.view;
    }
    return nil;
}

**Comment by rahulvyas** [comment]
@JyotiNS can you share more code example for load one page at a time ?
