### ISSUE TITLE
MXSegmentedPager background color

### ISSUE THREAD

**Issue by ravigupta049** [maxep/MXSegmentedPager#152]
Hi, 
I have been trying to set the segmented pager and all its components background colour to clear colour but i have not succeeded.
Can you please help me out in this?

**Comment by rajdhakate** [comment]
Hi Ravi, did you find any solution?

**Comment by ravigupta049** [comment]
Hi @rajdhakate 
Yes i was able to set the background colour to clear. So the problem with me was i was setting my main controller's view  background colour as white. So you just try setting each components colour as clear colour. I don't know how you are using it but hope this helps.

**Comment by rajdhakate** [comment]
@ravigupta049 Yes. I'll try. Thank you
