### ISSUE TITLE
MXSegmentedPager pages with different frame sizes. Layout issue.

### ISSUE THREAD

**Issue by JozefLipovsky** [maxep/MXSegmentedPager#156]
I am trying to use `MXSegmentedPager` with parallax header and 4 different `ViewControllers`. 

From these 4 VCs I would like to use 2 `TableViewControllers` and 2 regular `ViewControllers` with simple charts. The idea is to have half of the screen as Header and second half of the screen as Segmented pager.

As you can see from gif below, I am experiencing autolayout issues during the first scroll. I found out is, that after intial load `self.segmentedPager.pager` frame height is equal to first `SummaryViewController` (UITableViewController with static cells) frame height. Once I try this first initial scroll or once I tap different segment `viewDidLayoutSubviews` is called for the second time and `self.segmentedPager.pager` frame is resized correctly. 

I tried to solve this this by forcing layout update (setNeedsLayout + layoutIfNeeded on segmented pager or VCs) but no luck so far. Any idea or advice what should I focus on in this case? 

![](https://media.giphy.com/media/26gR0WLI87qJKgiVG/giphy.gif)

**Comment by maxep** [comment]
Hi @JozefLipovsky 
Do you have a sample project that reproduce your issue?

**Comment by JozefLipovsky** [comment]
Hi @maxep ,
I just created test project with the same setup I use in my App. Here is the [link](https://github.com/JozefLipovsky/SegmentedPagerControllerTest). Couple things I've noticed during troubleshooting:

1) I was trying to setup header height in `viewDidLayoutSubviews` (during `viewWillAppear` self.frame  has 0 height) to make sure I am setting header size to be exactly half of the segmentedPager frame `self.view.frame.size.height / 2` and this setup caused the incorrect layout.  Also I am getting `Unable to simultaneously satisfy constraints` warnings with this setup on `HeaderView`:

```
- (void)viewDidLoad {
    [super viewDidLoad];
    
    [self setupSegmentedPager];
}

- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    
    self.segmentedPager.parallaxHeader.height = self.view.frame.size.height / 2;
    self.segmentedPager.parallaxHeader.minimumHeight = self.view.frame.size.height / 2;
}


- (void)setupSegmentedPager {
    self.segmentedPager.parallaxHeader.view = self.headerView;
    self.segmentedPager.parallaxHeader.mode = MXParallaxHeaderModeFill;

    self.segmentedPager.segmentedControl.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationDown;
    self.segmentedPager.segmentedControl.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleWidth;
    self.segmentedPager.segmentedControl.selectionIndicatorHeight = 4.0;
    self.segmentedPager.segmentedControl.borderType = HMSegmentedControlBorderTypeBottom;
    self.segmentedPager.segmentedControl.selectionStyle = HMSegmentedControlSelectionStyleFullWidthStripe;
}
```

2) When I hardcode header height immediately in `setupSegmentedPager` method layout is OK:
```
- (void)viewDidLoad {
    [super viewDidLoad];
    
    [self setupSegmentedPager];
}

- (void)setupSegmentedPager {
    self.segmentedPager.parallaxHeader.view = self.headerView;
    self.segmentedPager.parallaxHeader.mode = MXParallaxHeaderModeFill;
    self.segmentedPager.parallaxHeader.height = 300;
    self.segmentedPager.parallaxHeader.minimumHeight = 300;
    
    self.segmentedPager.segmentedControl.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationDown;
    self.segmentedPager.segmentedControl.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleWidth;
    self.segmentedPager.segmentedControl.selectionIndicatorHeight = 4.0;
    self.segmentedPager.segmentedControl.borderType = HMSegmentedControlBorderTypeBottom;
    self.segmentedPager.segmentedControl.selectionStyle = HMSegmentedControlSelectionStyleFullWidthStripe;
}
```

I assume the issue may be the fact that in Header I have `MapView` which is `scrollView`?? Or maybe I am missing something else...

I found a workaround, just calculating header height with UIScreen, navBar and tabBar frame sizes:
```
   ....
    self.segmentedPager.parallaxHeader.view = self.headerView;
    self.segmentedPager.parallaxHeader.mode = MXParallaxHeaderModeFill;
    
    CGFloat segmentedPagerSize = [UIScreen mainScreen].bounds.size.height - self.navigationController.navigationBar.frame.size.height - self.tabBarController.tabBar.frame.size.height - [[UIApplication sharedApplication] statusBarFrame].size.height;
    
    self.segmentedPager.parallaxHeader.height = segmentedPagerSize / 2;
    self.segmentedPager.parallaxHeader.minimumHeight = segmentedPagerSize / 2;
   ....
```


But maybe you will be able to spot some other problem in my implementation?

**Comment by maxep** [comment]
Thanks @JozefLipovsky 
Have you tried to uncheck the `Adjust Scroll View Insets` of your `MXSegmentedPagerController` subclass?

**Comment by JozefLipovsky** [comment]
@maxep `Adjust Scroll View Insets` didn't help.

**Comment by maxep** [comment]
You are talking about the Summary table view that scroll off the screen right? because your test project does not reproduce the issue.

**Comment by JozefLipovsky** [comment]
Hi @maxep, as I explained in comment above (1.) , if I try to set header height in viewDidLayoutSubviews the issue is still there:
``` 
- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    
    self.segmentedPager.parallaxHeader.height = self.view.frame.size.height / 2;
    self.segmentedPager.parallaxHeader.minimumHeight = self.view.frame.size.height / 2;
}
```

**Comment by ranjitxsingh** [comment]
I am also facing same issue.
Please update here guys.
