### ISSUE TITLE
Load wrong controller

### ISSUE THREAD

**Issue by 3r1k83** [maxep/MXSegmentedPager#160]
I have three tab segnetpager. I use storyboard in obj-c. I have strange behavior, when I go from tab 1 to 2 the third controller is loaded. When I go from 3 to 2, first controller is loaded. This can be ok in my case, but when I go from 2 to 1 or 2 to 3 no controller is loaded. I want to load controller when I press be tab (for ex. I press the 1 and the 1 is loaded). 
I hope I explained myself :) 
Do I do something wrong? How is correct implementation?

**Comment by legendw84it** [comment]
Check if you reuse the same class reference instead of creating a new instance.

**Comment by 3r1k83** [comment]
What you mean exactly? Instance of the controllers I use? 
How can I check it? 
Have you some clear code example?
Thank you.

**Comment by maxep** [comment]
That is the regular behavior, it loads neighbors pages in case you start scrolling.

**Comment by 3r1k83** [comment]
Ok, i understand it, but I need to load the controller again when the user enter in a view. The view needs to reload when i press a tab, but viewDidLoad or viewDidAppear are not called. 
What do you suggest?

**Comment by agrafiotisA** [comment]
Maybe try with overriding the pager's delegate method:
```
override func segmentedPager(_ segmentedPager: MXSegmentedPager, didSelect view: UIView) {
        let selectedController = viewControllers[segmentedPager.segmentedControl.selectedSegmentIndex]

    }
```
Assuming you have some array of controllers past to your class, then you can create a method to the wanted ViewControlelr to call and reload the data.

**Comment by 3r1k83** [comment]
yes i tried but no success...
This is my code: 
-(void)segmentedPager:(MXSegmentedPager *)segmentedPager didSelectViewWithIndex:(NSInteger)index{

    switch (index) {
        case 0:{
            AddressBookContentViewController *vc = [[AddressBookContentViewController alloc] init];
            return;
        }
        case 1:{
            DialPadViewController *vc = [[DialPadViewController alloc] init];
            return;
        }
        case 2:{
            CallLogViewController *vc = [[CallLogViewController alloc] init];
            return;}
        default:
            return;
    }
}

**Comment by 3r1k83** [comment]
ok i managed to reload my data with notification: 
            [[NSNotificationCenter defaultCenter] postNotificationName:@"load" object:nil];
How can i disable the loading of other controllers? Now i want to load only the controller i select when i press the button
