### ISSUE TITLE
Fatal Exception: NSRangeException

### ISSUE THREAD

**Issue by ravigupta049** [maxep/MXSegmentedPager#162]
Hi maxep,
I have been getting this crash randomly. I couldn't point out anything yet. 
Can you please help me in this?

<img width="951" alt="screen shot 2017-05-25 at 3 11 31 pm" src="https://cloud.githubusercontent.com/assets/17566193/26445136/ac242880-415c-11e7-817a-769577a06be3.png">

**Comment by YkmLo** [comment]
hi @maxep , any updates on this?
