### ISSUE TITLE
Tableviewcells disappear with scrolling using a UITableView inside a child controller of MXSegmentedPagerController

### ISSUE THREAD

**Issue by sfkaos** [maxep/MXSegmentedPager#163]
Thank you so much for the MXSegmentedPager it has helped me out a lot with my current project.

However, I ran into an issue with the SegmentedPager with one of its children having a UITableView, and having a ContainerView as a parent view. I apologize if this sounds confusing. The UI is probably the most complex I've worked with.

It is made up of two container views - the first container view contains a simple UIView and is managed by a regular UIViewController subclass, the second container view is managed by my MxSegmentedPagerController subclass.

![lesson_storyboard_ _edited](https://user-images.githubusercontent.com/160737/27110463-6b611b8a-505e-11e7-86bc-fc1bbb306409.png)

The containerview for the MxSegmentedPagerController subclass has autolayout constraints that set the left, top, bottom, right to the main view, bottom of top container view, main view, main - respectively. I ALSO set the width equal to the width of the superview and the height to some constant value.

However, though the tableviewcells in the child controller of the MXSegmentedPagerController are displayed when the view is loaded, as soon as the tableview is scrolled on they all disappear.

![tableview_issue](https://user-images.githubusercontent.com/160737/27110987-ec493ae0-5061-11e7-8bc1-bd1b19c4bf8b.gif)

Stumped! Does anyone have any ideas?

I'm assuming it has something to do with UIScrollView and autolayout. When I remove MXSegmentedPagerController as the parent and have the child controller moved into the container view by itself, it works fine.

**Comment by jaddoescad** [comment]
Anyone?

**Comment by mujtuba11khan** [comment]
I am having the same issue as described above. Can anyone please help
@maxep
