### ISSUE TITLE
I can addSubView,someone help me!

### ISSUE THREAD

**Issue by itVietPham** [maxep/MXSegmentedPager#167]
I want to put addSubview at bottom of MXSegmentedPagerController but I can't do it
self.view.addSubview(bottomView) not work :(

**Comment by hardikamal** [comment]
@maxep @itVietPham is this possible?... Even i want to put a single button at the bottom which is visible in all the tabs

**Comment by harifsp** [comment]
@maxep how did you close this issue? got a solution?
