### ISSUE TITLE
Odd behavior : refreshcontroller

### ISSUE THREAD

**Issue by fredjahanmanesh** [maxep/MXSegmentedPager#179]
hi, when i use UIrefreshcontroller in pages, some issue happen in this code, i dont know why
when i use this code 

`segmentedPager.parallaxHeader.height = UIScreen.main.bounds.height/2.5
`

refresh controllers in subiews not working and nothing show, but when i change the height like this

`segmentedPager.parallaxHeader.height = 200
`

it will work well, i dont know why, even i can use this code too

`segmentedPager.parallaxHeader.height = CGFloat(Int(UIScreen.main.bounds.height/2.5))
`

and works well

**Comment by GustinLau** [comment]
help for me
