### ISSUE TITLE
Change Current Index

### ISSUE THREAD

**Issue by KushThakkar** [maxep/MXSegmentedPager#184]
When I want to load View Controller I want to show Second Tab Selected Directly.

**Comment by KushThakkar** [comment]
let when = DispatchTime.now() + 2 // change 2 to desired number of seconds
        DispatchQueue.main.asyncAfter(deadline: when) {
            // Your code with delay
             self.segmentedPager.pager.showPage(at: 1, animated: true)
        }

**Comment by hezhk3** [comment]
That's too ugly......
