### ISSUE TITLE
## background image setting

### ISSUE THREAD

**Issue by Manibhushan393** [maxep/MXSegmentedPager#185]
hi, This is Manibhushan M , how to set image as a backgaround.. we are able set color only. what about image. can u please help me

**Comment by johnrajahkkd** [comment]
I fixed it by the following code: 

```
        let backgroundImage = UIImageView(frame: UIScreen.main.bounds)
        backgroundImage.image = UIImage(named: "background.png")
        self.view.insertSubview(backgroundImage, atIndex: 0)
        segmentedPager.backgroundColor = UIColor(patternImage:chatImage.image!)        
```

Note: It'll set the background for the whole screen (including segmented view and header view).
