### ISSUE TITLE
Passing data to the pagerview.

### ISSUE THREAD

**Issue by ambujshukla-cdn** [maxep/MXSegmentedPager#187]
Hi,
I want to send the data to the controller which opens on one of the tab. So how can I send the data to the opened pagerViewController.

**Comment by sanjaybhansali108** [comment]
You can use Custom Delegate for passing the data to the pagerview.

**Comment by ambujshukla-cdn** [comment]
Hi Sanjay,
     Can you add some code to do so.

**Comment by FahriBilici** [comment]
i have same problem anyone can help ?

**Comment by maxep** [comment]
you can follow @sanjaybhansali108 suggestion
