### ISSUE TITLE
Programmatically scroll header or bottom part

### ISSUE THREAD

**Issue by HDBaggy** [maxep/MXSegmentedPager#188]
Kindly guide me how can I programmatically scroll the header or bottom part. 

 I tried by following code, but it changes the overall height of the header. I just want to scroll the segmented control. 

segmentedPager.parallaxHeader.height = 40

Kindly help me.

Thanks

**Comment by robzimpulse** [comment]
maybe this could help

>guard let contentView = view.subviews.flatMap({ $0 as? MXScrollView }).first else {return}
>contentView.setContentOffset(CGPoint(x: 0, y: 0), animated: true)
