### ISSUE TITLE
MXSegmentedPager.h:24:9: 'HMSegmentedControl.h' file not found

### ISSUE THREAD

**Issue by iimez** [maxep/MXSegmentedPager#19]
I added the pager to my swift project using cocoapods. The error in title appears when building the pod. I tried to install HMSegmentedControl as a seperate (sibling) dependency, but the result is the same. Any idea how I could fix this?

**Comment by maxep** [comment]
Well I don't know. Do you have the HMSegmentedControl files in your pods directory ?

**Comment by iimez** [comment]
Yes it is there. Tbh this looks like a problem related to xcode (and a swift project which uses an objectivec pod which has an objectivec dependency). I suspect that I need to add the header explicitly (bridging file does not seem to work). I'm going to play around with it some more, will post here once I get it working.

**Comment by LTe** [comment]
@Limezz any progress? I have the same issue
