### ISSUE TITLE
MXPagerViewController in conjunction with an opaque UITabBarController and UINavigationController has incorrect page bounds

### ISSUE THREAD

**Issue by Roost** [maxep/MXSegmentedPager#191]
A weird case occurs when using an opaque `UITabBarController`, where one of the tabs is a `MXPagerViewController` of which it's page is an initial `UINavigationController` via a SotryBoard.

It appears that the page adopts the bounds assuming the the `UITabBar` is within the `MXPagerView`. This only occurs when the `UITabBarController` is set to opaque. 

I have been unable to solve the issue with any combination of extending edges, or adjusting scrollView insets. Additionally, I am unable to track down where the frame is incorrectly adjusted.

A sample of the bug can been seen on this repository: https://github.com/Roost/MXPagerViewControllerTest.git

**Comment by cdigiacinto** [comment]
I have the same problem. 

Like you said the problem I think is the UITabBar

This is not a fix but if you try to add the UITabBar height the size is correct
MXPagerView.m (layoutSubviews):
`frame.size.height = frame.size.height + 49;`
