### ISSUE TITLE
Scrolling Disable From Parallax Header

### ISSUE THREAD

**Issue by KushThakkar** [maxep/MXSegmentedPager#193]
I want to scrolling only from bottom of Segment Control.

If user scrolling above the segment control that should be disable for that.

Please check below attachment for graphical representation of this issue.

![simulator screen shot 01-feb-2018 4 32 59 pm](https://user-images.githubusercontent.com/17953979/35675471-21e849ca-076e-11e8-8cb9-911fb848a55f.png)

Let me know if you need more Clarification.

**Comment by KushThakkar** [comment]
Write below code in **MXScrollView.m**

-(BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer{
    CGPoint point =  [gestureRecognizer locationInView:self.parallaxHeader.view];
    if(CGRectContainsPoint(self.parallaxHeader.view.frame, point))
        return NO;
    return YES;
}

**Comment by Evyasafmordechai** [comment]
[](https://github.com/maxep/MXSegmentedPager/issues/211
)

**Comment by Evyasafmordechai** [comment]
[https://github.com/maxep/MXSegmentedPager/issues/211](url)

**Comment by NileshKalathiya** [comment]
@KushThakkar  can you please explain this? I want to do the same
