### ISSUE TITLE
Add a view above Pagerview / set top inset / offset

### ISSUE THREAD

**Issue by bhavinpankanis** [maxep/MXSegmentedPager#194]
Hey, 
I have a requirement wherein I need to show a custom view on top of the pagerview.
I do not want the segment control to scroll beyond it.

Any inputs how that be achieved ?. I referred to this https://github.com/maxep/MXSegmentedPager/issues/52 and https://github.com/maxep/MXSegmentedPager/issues/34 but not sure how to proceed.

Thanks in advance

**Comment by Hashir524** [comment]
Any Luck?
