### ISSUE TITLE
How to make the translucent property on the navigationbar and segmented pager to false in swit

### ISSUE THREAD

**Issue by RaviMehta90** [maxep/MXSegmentedPager#196]
Hi,

I am facing the following problem while using the library.
Throughout my app i have made the translucent property of the navigation bar to 'false' so that i dont get the blur effect on the navigation bar.

After integrating the library on a viewcontroller, that viewcontroller's navigationbar's translucent property is automatically set to 'true'

![img_0003](https://user-images.githubusercontent.com/35226239/36628858-526b3c16-1974-11e8-98b3-474f23d84bb5.jpg)

I am trying to make the nav bar and segment bar the same color as my header view but it seems there is a translucent property added to the MXSegmentedPagerController

Please let me know how can i change the translucent property to false

**Comment by ajithkumark771** [comment]
I met with same kind of problem, a translucent layer above segmented control. Solved it by changing selection indicating box's opacity to 1.0 . `MXSegmentedPager.segmentedControl.selectionIndicatorBoxOpacity = 1.0; `
