### ISSUE TITLE
How to support like this segmentcontrol?

### ISSUE THREAD

**Issue by xhzengAIB** [maxep/MXSegmentedPager#2]
Hi! @maxep 
Thank you, open source is cool.

![f92f6dc7-fbac-49b1-ad40-48ae36857915](https://cloud.githubusercontent.com/assets/1969908/6901686/87f38d34-d741-11e4-9f48-b1afa728466c.png)

the selected item is highlighted.

not selected item is two color, blackColor at top and grayColor at bottom. look this picture

**Comment by maxep** [comment]
Hi,

To customize the segmented control, you should refer to [HMSegmentedControl](https://github.com/HeshamMegid/HMSegmentedControl). As far as I know, it is not possible to have 2 lines text in the title..

**Comment by xhzengAIB** [comment]
@maxep 
I'm sorry, i miss this comment, i will be change the segmented control in my UI component, 
Thank you again for your reply.

Jack

**Comment by inPhilly** [comment]
I think he wants to know how to use a different type of segmented control. I would also be interested in this.

**Comment by maxep** [comment]
oh ok, sorry for the misunderstanding.
Well it wont be difficult to use another one but it all depend on the implementation you use!

The initialization is done in the segmentedControl property directly:

``` objective-c
- (CoolSegmentedControl *)segmentedControl {
    if (!_segmentedControl) {
        _segmentedControl = [[CoolSegmentedControl alloc] init];

        //Initialization here

        [self addSubview:_segmentedControl];

        self.moveSegment = YES;
    }
    return _segmentedControl;
}
```

Then setup titles in the reloadData method:

``` objective-c
- (void)reloadData {

    [...]

    self.pages = pages;
    self.keys = keys;

   //Setup you titles here, all titles or in the keys array

    [self layoutContainer];
}
```

Then when the segmented-control's index change, the following code should be called:

``` objective-c
    NSInteger index = //Get the index from the segment-control

    CGFloat x = self.frame.size.width * index;
    self.moveSegment = NO;
    [self.container setContentOffset:CGPointMake(x, 0) animated:YES];
    [self changedToIndex:index];
```

Finally,  to change the segmented-control's index when user swipe the page:

``` objective-c
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {

    if (self.moveSegment && scrollView == self.container && self.pages.count > 1) {
            NSInteger curIndex = //Get the index from the segment-control

            [...]
        }
        if (curIndex != index) {
            //Set you segmented-control's index here
            [self changedToIndex:index];
        }
    }
}
```

I think thats it!
