### ISSUE TITLE
Add new updates to pod

### ISSUE THREAD

**Issue by hardikamal** [maxep/MXSegmentedPager#20]
pod update not downloading the latest update...please update the pod to the latest commit...Thanks

**Comment by maxep** [comment]
Hi!

Not yet, I have other features to update. To wait, you can use :

```
pod 'MXSegmentedPager', :git => 'https://github.com/maxep/MXSegmentedPager.git'
```

**Comment by hardikamal** [comment]
:+1:

**Comment by maxep** [comment]
Hi @hardikamal ,

I've release the version 1.2 on cocoapods. I keep the new features for the next version.

**Comment by hardikamal** [comment]
Hi @maxep,

thanks bro.
