### ISSUE TITLE
Swift version upgrading issue 

### ISSUE THREAD

**Issue by dbalusu** [maxep/MXSegmentedPager#204]
Module compiled with Swift 4.0.2 cannot be imported in Swift 3.3: /Users/Framework/MXSegmentedPager.framework/Modules/MXSegmentedPager.swiftmodule/x86_64.swiftmodule

I could not build or run my project due to above w=error in Xcode 9.3

**Comment by agrafiotisA** [comment]
Find the framework in the pods project and then search for SWIFT_VERSION on the build settings and check if you have SWIFT4 version set. Not sure but this is what I did with some pods in the past.
