### ISSUE TITLE
How do i reuse webview class with different web urls??

### ISSUE THREAD

**Issue by hardikamal** [maxep/MXSegmentedPager#21]

**Comment by hardikamal** [comment]
@maxep  brother any solution to this??

**Comment by maxep** [comment]
Hi! Well you should set the url and reload the webview in the `segmentedPager:viewForPageAtIndex:`, see the UIWebView documentation.

**Comment by hardikamal** [comment]
Ahh sorry for any inconvenience....And thanks for the prompt response
