### ISSUE TITLE
Unable to scroll if I set header height to a fixed value

### ISSUE THREAD

**Issue by rahulvyas** [maxep/MXSegmentedPager#210]
In my case I want header to be there permanent. Let's say set header height to 200 and minimum header height to 200. But after setting this my child view controller's  table view doesn't scroll up. It kinda stuck.
Anybody knows any solution for fixed header height and smooth scrolling of child view controllers ?

**Comment by ChiragKothiya1996** [comment]
set minimum header height to 0.
