### ISSUE TITLE
Disable the parallax effect while scrolling up

### ISSUE THREAD

**Issue by Evyasafmordechai** [maxep/MXSegmentedPager#211]
I would like to disable the parallax effect while scrolling up.
I set `segmentedPager.bounces = false` to disable parallax when scrolling down but I don't know how to disable when scrolling up.

How can I do it?

Thank you for any help

**Comment by Evyasafmordechai** [comment]
I managed to do it by changing the method:  layoutContentView inside **MXParallaxHeader.m**
the result:

```
- (void)layoutContentView {
    CGRect frame = (CGRect){
        .origin.x       = 0,
        .origin.y       = -self.height,
        .size.width     = self.scrollView.frame.size.width,
        .size.height    = self.height
    };
    self.contentView.frame = frame;
    CGFloat div = self.height - self.minimumHeight;
    self.progress = (self.contentView.frame.size.height - self.minimumHeight) / (div? : self.height);
}
```

**Comment by knowsudhanshu** [comment]
Any update on this feature?
