### ISSUE TITLE
Crashing at scrollViewDidScroll

### ISSUE THREAD

**Issue by unoiatech** [maxep/MXSegmentedPager#213]
I am using crashlytics for crash reporting in my app and it is showing this crash.

> Fatal Exception: NSInvalidArgumentException
> -[MXPagerViewDelegateForwarder scrollViewDidScroll:]: unrecognized selector sent to instance 0x1c062c440

I am unable to understand what this crash means.

**Comment by rahulvyas** [comment]
I am also getting the same crash.
