### ISSUE TITLE
Any delegate method which is called when viewappears?

### ISSUE THREAD

**Issue by hardikamal** [maxep/MXSegmentedPager#215]
Hi @maxep 

Is there any delegate method which is called when viewappears, also for the 1st view when it is set below the tabs?

**Comment by dharmeshpatoliya** [comment]
@hardikamal Yes I have a same problem

**Comment by hardikamal** [comment]
@dharmeshpatoliya Any solution found for this?

**Comment by Saulenco** [comment]
as @maxep  mention in one of the reply's "You can add a target to the segmented control to get the segment selection." .
Tested: works
