### ISSUE TITLE
Extra White Space on Bottom of MX_pages

### ISSUE THREAD

**Issue by tadeha** [maxep/MXSegmentedPager#222]
Hello, I'm using container view to embed an MXSegmentedPagerViewController, everything is ok with view controllers connected to the pager but when I embed navigation controller to view controllers (pages) it causes an extra white space on the bottom of VC. It solved when I added a negative bottom space to views in view controller but I'm sure there should be an easier and better way to solve this problem! Looking forward to hear from you ;)

**Comment by YuanJiaShuai** [comment]
Hello, I also had this problem at that time. I solved the problem by adjusting the following properties. I hope it is useful for you.
```
@property(nonatomic,assign) UIRectEdge edgesForExtendedLayout;
@property(nonatomic,assign) BOOL extendedLayoutIncludesOpaqueBars;
@property(nonatomic,assign) BOOL automaticallyAdjustsScrollViewInsets;
```

**Comment by tadeha** [comment]
Thank you! @YuanJiaShuai
