### ISSUE TITLE
Scrollview delegate methods for child view are not called

### ISSUE THREAD

**Issue by hardikamal** [maxep/MXSegmentedPager#224]
Hi,

Scrollview delegate methods for child view are not called for table view.

    func scrollViewDidScroll(scrollView: UIScrollView) {
        if selectedIndex == 1 {
        if (self.lastContentOffset < scrollView.contentOffset.y) {
            // moved to top
            print("Up")
            let userInfo:[String:Any] = ["show":false]
            NotificationCenter.default.post(name: Notification.Name(Constants.NotificationIdentifier.refreshAddressList), object: self, userInfo:userInfo)
        } else if (self.lastContentOffset > scrollView.contentOffset.y) {
            // moved to bottom
            print("Down")
            let userInfo:[String:Any] = ["show":true]
            NotificationCenter.default.post(name: Notification.Name(Constants.NotificationIdentifier.refreshAddressList), object: self, userInfo:userInfo)
        } else {
            // didn't move
            print("Not moving")
        }
        self.lastContentOffset = scrollView.contentOffset.y
    }

Any solution?

**Comment by mmernissi** [comment]
Did anyone find the solution for this?
