### ISSUE TITLE
RTL and localization 

### ISSUE THREAD

**Issue by hamidire** [maxep/MXSegmentedPager#226]
Is there any support for localization, especially for RTL language. it seems ,it doesn't respect to the default RTL support of iOS, how can I use it for multiple language and RTL?

**Comment by ShimaDarya** [comment]
What do you exactly want?

**Comment by hamidire** [comment]
for example, I have 3 tabs , I want it to be like this:
tab1  tab2  tab3 --> in English
tab3 tab2  tab1  --> in Persian
but now it is like this:
tab1  tab2  tab3 --> in English and Persian

**Comment by ShimaDarya** [comment]
you should transform it

**Comment by hamidire** [comment]
I tried to but i didn't get any success

**Comment by magnett** [comment]
It's not just the order of the tabs, it's also the alignment. In the attached screenshots you will see how our Android app handles this correctly using native controls and how the iOS app version looks like.
![Simulator Screen Shot - iPhone X - 2019-07-04 at 10 40 07](https://user-images.githubusercontent.com/1730803/60648710-2316aa80-9e49-11e9-8ebd-ec3113ad2696.png)
![Screenshot_20190704-103539_InstaShop](https://user-images.githubusercontent.com/1730803/60648714-2742c800-9e49-11e9-9e7c-0a62be6f23af.jpg)

**Comment by magnett** [comment]
Please re-open, the issue still stands

**Comment by kyriakopoulos** [comment]
Any update on this ? This was closed automatically without any response
