### ISSUE TITLE
Transparent NavigationBar parallaxHeader not working

### ISSUE THREAD

**Issue by amodkanthe** [maxep/MXSegmentedPager#236]
Navigation bar is transparent

following is code for that
```
        super.viewWillAppear(true)
        let navigationBar = self.navigationController?.navigationBar
        navigationBar?.setBackgroundImage(UIImage(), for: .default)
        navigationBar?.shadowImage = UIImage()
        navigationBar?.isTranslucent = true
        navigationBar?.backgroundColor = .clear
```

Following is code to set TopAnchor

```
 DispatchQueue.main.async {
                if let window = appDelegate.window {
                    self.topBGView.topAnchor.constraint(equalTo: window.topAnchor).isActive = true
                }
            }
```

Following is code for parallax header
```
 viewControllerArray.append(tabVC)
            segmentedPager = MXSegmentedPager()
            self.segmentedPager.frame = self.view.bounds.inset(by: self.view.safeAreaInsets)
            view.addSubview(segmentedPager)
            view.bringSubviewToFront(segmentedPager)
            segmentedPager.dataSource = self
            segmentedPager.delegate = self
            segmentedPager.backgroundColor = .green
            segmentedPager.parallaxHeader.view = topBGView
            segmentedPager.parallaxHeader.mode = .fill
            segmentedPager.parallaxHeader.height = topBGView.frame.height
            segmentedPager.parallaxHeader.minimumHeight = 10
            segmentedPager.parallaxHeader.delegate = self
            segmentedPager.reloadData()
```

But NavigationBar is not appearing transparent also it seems to appear above header view
following is screenshot

<img width="293" alt="Screenshot 2019-08-14 at 8 02 57 PM" src="https://user-images.githubusercontent.com/5066441/63030754-7e1fd080-bed0-11e9-9c26-3139fc4f6c4d.png">

Tried hiding NavigationBar it looks like below means TopAnchor constraint code is working but somehow the NavigationBar is not appearing transparent

Following is image after hiding navigation bar
<img width="386" alt="Screenshot 2019-08-14 at 8 12 54 PM" src="https://user-images.githubusercontent.com/5066441/63030867-b58e7d00-bed0-11e9-9810-ddff30d1ff6d.png">

**### Also tried toggling Extend Edges Under TopBar in storyboard but no effect what so ever.**

After enabling extend edges under top bar it working fine but status bar is not appearing transparent

After adding below code as well it is not working

```
 let statusBar = UIApplication.shared.value(forKeyPath: "statusBarWindow.statusBar") as? UIView
            statusBar?.backgroundColor = UIColor.clear
```

Following is screenshot after enabling extend edges under top bar 
<img width="347" alt="Screenshot 2019-08-15 at 1 14 23 PM" src="https://user-images.githubusercontent.com/5066441/63084306-86c3e580-bf68-11e9-9d9a-2a0cff7e8f91.png">

**Comment by hardikamal** [comment]
@amodkanthe Were you able to achieve this?

**Comment by amodkanthe** [comment]
yes download sample app MXSegmentedPager and check how it is implemented in storyboard just refer to storyboard part first

**Comment by hardikamal** [comment]
@amodkanthe I tried running that but it does not have the navigation bar. I have a navigation bar with a back button. How do I achieve this?
