### ISSUE TITLE
MXSegmentedPager with Navigation Controller

### ISSUE THREAD

**Issue by WilliamHua** [maxep/MXSegmentedPager#24]
Does MXSegmentedPager remove the navigation controller from displaying? I have a MXSegmentedPager embedded in a navigation controller (logging self.navgiationController outputs a NavigationController object) and it doesn't seem to show up (the nav bar).

**Comment by maxep** [comment]
Not sure to understand... the MXSegmentedPager is a UIView subclass, it does not have access to the navigation controller.

**Comment by hardikamal** [comment]
Hi @maxep 

I have add button in navigation bar of parent viewcontroller which extends MXSegmentedPagerController...how can i access the add button from childviewcontroller...I tried instantiating the parentviewcontroller in child and accessing the add button...but it doesnt seems to work...

Thanks.

**Comment by maxep** [comment]
I' dont get what you trying to achieve... You can save a ref to your child in your parent controller.

**Comment by hardikamal** [comment]
I want to access the navigation bar from the tab view...is it possible?

**Comment by maxep** [comment]
Yes it's possible, you can forward the button action to the selected page.

**Comment by hardikamal** [comment]
can u tell me how to do it... i tried creating instance of parenttabviewcontroller in containerviewcontroller and then access the button but it did not work...

**Comment by maxep** [comment]
I'm sorry @hardikamal, but it's not the right place to do so.. You can open an issue with a 'help wanted' label and fill it up with sample code and a full explanation of what you attempt to do (it is still not clear to me). or you can use stackoverflow to reach more people.
