### ISSUE TITLE
didSelectViewWith not fired

### ISSUE THREAD

**Issue by seraph3b** [maxep/MXSegmentedPager#240]
in latest version didSelectViewWith change name in didSelectViewAt and it's not fired on pages change anymore, is there some work around for having similar behaviour or it's a bug?

following class protocols:

class MyViewController: MXSegmentedPagerController, MXParallaxHeaderDelegate {
....

**Comment by tadeha** [comment]
I have the same problem

**Comment by ninholli** [comment]
I have the same problem
