### ISSUE TITLE
Selected Segment - scroll issue

### ISSUE THREAD

**Issue by dhruvit-e2logy** [maxep/MXSegmentedPager#247]
Selected segment control with selection indicator displays to left or right instead of center.

* When selecting any segment, it scrolls to left or right side of the screen.
* I have used this library before and it was working properly. But after updating pods it is not working as it was before.

Selected segment should display in center of the screen not on right or left of the screen.

Is there any way to make it working as it was before ?
Can you please help me out for this issue ?

**Comment by PadharO** [comment]
I'm facing the same issue, after updating the library.
Did you find any solution??

**Comment by Ubaid-Javaid** [comment]
TableView Scroll is not working when i attched HeaderView

**Comment by truhoada** [comment]
> TableView Scroll is not working when i attched HeaderView

after all config, call:

>         segmentedPagerView.layoutIfNeeded()

**Comment by ramezadnan2020** [comment]
how to stop scroll for view header ??

**Comment by amodkanthe** [comment]
Anyone found any solution on this ? Facing similar issues after updating pod.

**Comment by varunsdcet** [comment]
TableView Scroll is not working when i attched HeaderView

**Comment by neobie** [comment]
Same issue with varunsdcet. I wonder is this working for swift ? There is no Parallax working example for Swift too.

**Comment by neobie** [comment]
I notice in Swift, the parallax only activated after I initiate device rotation. 
The cover image also display out of the screen , expands to the right.
Gets normal after rotating device.
Any help ?

**Comment by varunsdcet** [comment]
@neobie  segmentedPagerView.layoutIfNeeded() call on viewdidload() working in my case
