### ISSUE TITLE
HeaderView shifted towards left and scroll not working after update

### ISSUE THREAD

**Issue by amodkanthe** [maxep/MXSegmentedPager#248]
HeaderView is shifted to left of screen and scroll is not is not working after updating 
Following is my code

This strange behaviour is happening after update it was working fine before

    `    view.addSubview(segmentedPager)
        segmentedPager.dataSource = self
        segmentedPager.delegate = self
        segmentedPager.pager.delegate = self
        segmentedPager.parallaxHeader.view = topBGView
        segmentedPager.parallaxHeader.mode = .fill
        segmentedPager.parallaxHeader.height = topBGView.frame.height
        segmentedPager.parallaxHeader.minimumHeight = view.safeAreaInsets.top
        segmentedPager.parallaxHeader.delegate = self
        segmentedPager.bounces = false
        segmentedPager.segmentedControl.indicatorColor = UIColor.black
        segmentedPager.segmentedControl.selectedTextColor = UIColor.black
        segmentedPager.segmentedControl.borderColor = .white
        segmentedPager.segmentedControl.font = FontStyle.ProximaNovaSemibold(size: 15)
        segmentedPager.segmentedControl.backgroundColor = .white
        segmentedPager.segmentedControl.indicatorHeight = 3.0
        segmentedPager.segmentedControl.borderColor = .white

      override func viewWillLayoutSubviews() {
        self.segmentedPager.frame = CGRect(origin: CGPoint.zero, size: view.frame.size)
        super.viewWillLayoutSubviews()
     }

    override func viewDidLoad() {
        
        super.viewDidLoad()
        
        segmentedPager = MXSegmentedPager()
    }`

![Simulator Screen Shot - iPhone 11 - 2020-05-13 at 00 50 14](https://user-images.githubusercontent.com/5066441/81736475-458b4280-94b4-11ea-8a4b-76f7487f9599.png)

**Comment by amodkanthe** [comment]
Found that Mainly happening due to MXParallaxHeader moving back to version 'MXParallaxHeader', '~> 1.0.0' works fine

**Comment by MuseerAnsari** [comment]
@amodkanthe I stuck with latest version and spend around 2 hours. but your comment save my day. thank you!

**Comment by neobie** [comment]
cant believe bug is not fixed for months.
