### ISSUE TITLE
didSelectViewWithIndex called multiple times

### ISSUE THREAD

**Issue by WilliamHua** [maxep/MXSegmentedPager#25]
I have a MXSegmentedPager with two lists and a parallax header. 

I am implementing the method

 `- (void)segmentedPager:(MXSegmentedPager *)segmentedPager didSelectViewWithIndex:(NSInteger)index` 

to change the parallax header whenever the list changes (I change the imageView's image).

I animate the change of pictures for .5 seconds to make it a bit smoother. Whenever I transition from the first tab to the second, the animation is fine. However, on certain instances, when I change from tab two to tab one, the animation doesn't work.

I logged a message whenever the animation started and when it finished and it seemed that the animation was starting twice. I then put a log at the beginning of the method and confirmed that the method was indeed called twice when switching from the second tab to the first one.

**Comment by maxep** [comment]
I will check this!

**Comment by maxep** [comment]
Fixed in 91821ba1cd1ca28889a9fc87787f5564acff2973
