### ISSUE TITLE
Cannot scroll vertically on iOS 12 and 13

### ISSUE THREAD

**Issue by liennh** [maxep/MXSegmentedPager#259]
on iOS 14, it works well. But on iOS 12 and 13, it is freezed

**Comment by daniyalyousuf07** [comment]
same scrolling is not working for me either on ios 13

**Comment by HideOnBushTuT** [comment]
same error and any help ?? and the `parallaxHeader.progress`  returns the wrong value !

**Comment by HideOnBushTuT** [comment]
it will work if device rotate ! but don't know why @maxep

**Comment by HideOnBushTuT** [comment]
> i find the easiest way to resove this problem is let the `MXSegmentedPager` "reload" once
```swift
pager.setNeedsLayout()
pager.layoutIfNeeded()
```
