### ISSUE TITLE
NSInternalInconsistencyException error

### ISSUE THREAD

**Issue by cerupcat** [maxep/MXSegmentedPager#26]
It's hard to say if this is my code implementation or something in MXSegmentedPager that needs to remove obserever. I'm getting the followed error when removing a view that has a MXSegmentedPager.

 `*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x137577700 of class MXPagerView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x170c55e40> (
<NSKeyValueObservance 0x1702d4cf0: Observer: 0x137577700, Key path: contentOffset, Options: <New: YES, Old: YES, Prior: NO> Context: 0x100ab23f0, Property: 0x17084e4c0>
<NSKeyValueObservance 0x1702d4b30: Observer: 0x137577700, Key path: contentSize, Options: <New: NO, Old: NO, Prior: NO> Context: 0x100ab23f0, Property: 0x170851fd0>`

**Comment by cerupcat** [comment]
Looks like observers aren't getting fully removed. I can submit a pull request when I get a sec, otherwise adding this to the MXPageView dealloc fixed it:

```
- (void)dealloc {
    [self removeObserver:self forKeyPath:NSStringFromSelector(@selector(contentOffset)) context:kMXPagerViewKVOContext];
    [self removeObserver:self forKeyPath:NSStringFromSelector(@selector(contentSize)) context:kMXPagerViewKVOContext];
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}

```

**Comment by maxep** [comment]
Yes your are fully right!! Actually, I did make this fix but somehow it didnt get commit :/ 

I guess it's enough like this:

``` objective-c
- (void)dealloc {
    [self removeObserver:self forKeyPath:NSStringFromSelector(@selector(contentOffset)) context:kMXPagerViewKVOContext];
    [self removeObserver:self forKeyPath:NSStringFromSelector(@selector(contentSize)) context:kMXPagerViewKVOContext];
}
```

**Comment by cerupcat** [comment]
@maxep  Can you bump the podspec so this fix is in the latest pod? Thanks! :)

**Comment by jwardle** [comment]
+1 Seeing this error - waiting for updated podspec :)

**Comment by maxep** [comment]
pod updated ! sorry for the delay..

**Comment by Suntw** [comment]
+1 waiting for updated popspec
