### ISSUE TITLE
Resizing tableView 

### ISSUE THREAD

**Issue by chlebta** [maxep/MXSegmentedPager#27]
Hello, I'm trying to resize my tableView width by updating the frame of tableview but doesn't worked , I've tried to update tableview with at creation time, at viewWillAppear, tied to change cell Size at cellForRow... but none of them worked any help over here ?

**Comment by maxep** [comment]
Hi @chlebta 

Yes pages fills the pager space, so setting frames of pages wont have effect. To do so, you should add your tableView as a subview of a superview and add that superview as page.
