### ISSUE TITLE
How to add a pulltorefresh function

### ISSUE THREAD

**Issue by HustHank** [maxep/MXSegmentedPager#29]
If I want to add a pull to refresh function, how can I do that?
Or when the header had scrolled down to the bottom(without stretched), how can I just scroll down the tableview to pull to refresh. Thanks

**Comment by maxep** [comment]
Hi @cctvzxxz1 

You can use the progressBlock property in the ParallaxHeader category to know the scroll position. Then you can use this value to set the progress position of a progress view like one of the [M13ProgressSuite](https://github.com/Marxon13/M13ProgressSuite).
You also can use this value to scroll down the current page.

**Comment by HustHank** [comment]
Thank you for your reply, my problem had been solved ^_^

**Comment by HustHank** [comment]
Hi,
     I had found somebody implement the same functions like you,as the link follows:  
     https://github.com/akiroom/AXStretchableHeaderTabViewController
     and I found he gave headerView a property(bounces), like UIScrollView 's property (bounces), just when scroll down at bottom(do not make the headerView been stretched and the segmentControl stay at the position that below the headerView, just the tableView scroll down), like the picture as follows:
![picture](https://cloud.githubusercontent.com/assets/5294259/8270400/46381e94-1811-11e5-931f-271b56056c84.gif)

Though I want to edit your code by myself,  I find that I do not know how to do it, because your code is  so good, I can not find a way to start.

So please help me to find  a way to edit your code like that,Thank you.

**Comment by maxep** [comment]
Hi @cctvzxxz1 
I'm currently on vacation, I will get back to you when I get back home in 2 weeks,
Regards

**Comment by cerupcat** [comment]
I'm also wondering what the best way to add this would be. @cctvzxxz1 are you looking to add the refresh at the top or under the segmentedPager?

**Comment by jwardle** [comment]
~~Shouldn't you handle this in the view you add to the particular segment page, rather than rely on support from the library. I would assume you could add a TableView to the 'page' you are going to show, and add the refresh control to that tableview. The tableview is still a scroll view, therefore you should be able to do this as you would with any normal TableView component outside of the pager.~~

**Comment by cerupcat** [comment]
Hi @jwardle, It's more an issue with the parallax view. Simply adding a UIRefreshControl doesn't work.

**Comment by kaushalradix** [comment]
Hi @cctvzxxz1 I have same problem whatever you have. Please reply  if solved isue mentioned by cctvzxxz1. Thanks

**Comment by maxep** [comment]
Hi everyone,

I've added a quick implementation of a refresh control in the Parallax example which will reload the webview. It uses the [M13ProgressSuite](https://github.com/Marxon13/M13ProgressSuite).

@cerupcat is right, you cannot add a UIRefreshControl to pages using the ParallaxHeader for the simple reason that your pages will no more bounce, the pager does instead.

Hope this will help!

**Comment by calios** [comment]
Hi, @maxep what if I want to add pull down to refresh and pull up to reload more for tableview using MXSegmentedPager? It will be fantastic to hear your suggestion on this problem, because it has cost me a long time trying it.

**Comment by maxep** [comment]
Hi @calios 

I've just added a `bounces` property which you should set to NO if you want to use your embedded refresh controls. It will behaves like @cctvzxxz1's picture. Hope this help.

**Comment by CavalcanteLeo** [comment]
Didn't understand how to do it

**Comment by Evyasafmordechai** [comment]
segmentedPager.bounces = false 
Works great, tnx

**Comment by ShimaDarya** [comment]
I need the exact code and I don't want to disable the bouncing feature of header view and when pull to refresh the table view reload its data
