### ISSUE TITLE
Prohibiting Horizontal Scrolling between Views

### ISSUE THREAD

**Issue by inPhilly** [maxep/MXSegmentedPager#30]
I cannot find a way to keep the user from scrolling between the views using horizontal gestures. I want to allow the user to tap the segmentedControl to change views, but I do not want the control to recognize and respond to horizontal gestures. I use several tableviews and I need the swipe to delete functionality; the tableview currently doesn't recognize swipe to delete since this gesture currently will only scroll between the views. I am using MXSegmentedPager only. Tried to remove the gesture recognizer delegate (among other things) and it did not work.

**Comment by maxep** [comment]
Hi!

To do so, you can disable the pager to scroll by 

``` objective-c
self.segmentedPager.pager.scrollEnabled = NO;
```

And if you don't want your pager to have an animation even when you tap on the control, you can set the 'Tab Transition Style' :

``` objective-c
self.segmentedPager.pager.transitionStyle = MXPagerViewTransitionStyleTab;
```

**Comment by inPhilly** [comment]
Perfect! Thank you.
