### ISSUE TITLE
updateParallaxHeaderViewHeight missing

### ISSUE THREAD

**Issue by electic** [maxep/MXSegmentedPager#32]
VGParallaxHeader implements updateParallaxHeaderViewHeight, which is not exposed here.

**Comment by jwardle** [comment]
+1

**Comment by maxep** [comment]
Hi,

The header height is not in the current release (0.0.6). I will expose the property as soon as its available in a release.

**Comment by maxep** [comment]
I've added the latest VGParallaxHeader code into the repo while waiting for the next release. The `updateParallaxHeaderViewHeight` method is now exposed.
