### ISSUE TITLE
Question: View above the HMSegmentedControl

### ISSUE THREAD

**Issue by jwardle** [maxep/MXSegmentedPager#34]
Is there a way to insert a static (i.e. non parallax) view above the HMSegmentedControl - so the control does not appear at the top of the screen. For instance, if one wanted to put content above the control that shows regardless of selected segment. 

Or is VGParallaxHeader the preferred approach to this - but 'turning off' the parallax effect?

**Comment by jwardle** [comment]
Any thoughts on how best to achieve this?

**Comment by maxep** [comment]
Hi @jwardle 

I think you can use the sticky view property of the VGParallaxHeader but I'm not sure to understand well what you want to achieve..

**Comment by jwardle** [comment]
That is one way to achieve it I guess. I was more referring to a view above the HMSegmentedContol - like a TableView Header view, rather than having to use the parallax header, as one may not want the view above the segmented control to be 'parallaxed'. Does that make more sense?

**Comment by maxep** [comment]
If you don't want a parallax effect, you can use the `VGParallaxHeaderModeCenter` or `VGParallaxHeaderModeTop` when you set your header. But it wont be like a tableview header, I guess you would need a `VGParallaxHeaderModeBottom` but it doesn't exist. I think the sticky view property would do the trick.
