### ISSUE TITLE
Request: Ability to support space between pages like UIPageView

### ISSUE THREAD

**Issue by jwardle** [maxep/MXSegmentedPager#35]
I can't see any reference to a property supporting space between the page views within MXSegmentedPager and associated classes - apologies if I have missed it. 

It would be nice to be able to support a 'gutter' between the page views like the UIPageView's UIPageViewControllerOptionInterPageSpacingKey option.

**Comment by maxep** [comment]
Yes you are right. I will check that. Thanks!
