### ISSUE TITLE
Reuse UIViewController for multiple tabs

### ISSUE THREAD

**Issue by hardikamal** [maxep/MXSegmentedPager#38]
Hi @maxep 

Once again thanks for the awesome library...Is it possible to reuse the view controller..the way we reuse the uiview...my task is to create dynamic list of products under different categories which are dynamic..So i want to use a viewcontroller which has tableview in it and reuse that viewcontroller for multiple categories...

Thanks

**Comment by maxep** [comment]
Hi @hardikamal 

Reuse registration from class should work with view controller but not from nib. In a MXSegmentedPagerController subclass, you can try this:

``` objective-c
- (void)viewDidLoad {
    [super viewDidLoad];

    //Register your view controller as page
    [self.segmentedPager.pager registerClass:[CustomViewController class] forPageReuseIdentifier:@"PageIdentifier"];
}

- (UIViewController *)segmentedPager:(MXSegmentedPager *)segmentedPager viewControllerForPageAtIndex:(NSInteger)index {
    //Dequeue reusable page
    CustomViewController *page = [segmentedPager.pager dequeueReusablePageWithIdentifier:@"PageIdentifier"];

    //Prepare your page

    return page;
}
```

**Comment by maxep** [comment]
Sorry my mistake, it wont work with class neither. The reuse identifier is associated with a UIView.
Do you want to register a UIViewController from class or from nib ?

I have added a fix to get it work with class registration. But be careful by using the latest code, I have merge the MXSegmentedPager with the ParallaxHeader category, which mean you have to change `#import "MXSegmentedPager+ParallaxHeader.h"` to `#import "MXSegmentedPager.h"`

**Comment by hardikamal** [comment]
@maxep  is it possible to do it from storyboard viewcontroller?

**Comment by maxep** [comment]
No it wont be possible with reusable nib, the solution would be to create a custom segue and use it to get pages. But it's not possible with the current implementation. I will think about a solution.

**Comment by maxep** [comment]
I have added a storyboard support. You can check the Storyboard example to use UIViewController from segue.

**Comment by yermukhanbet** [comment]
Hi! I was wondering, how to register the child view controllers in class, with no storyboard?
