### ISSUE TITLE
How to set the height of the segmentedControl?

### ISSUE THREAD

**Issue by DesmondPang** [maxep/MXSegmentedPager#39]
I tried to set the frame of segmentedControl but it does work. 
self.segmentedPager.segmentedControl.frame = CGRectMake(10, 10, 300, 60);

**Comment by maxep** [comment]
You should implement the delegate method:
 `- (CGFloat) heightForSegmentedControlInSegmentedPager:(nonnull MXSegmentedPager*)segmentedPager;`
