### ISSUE TITLE
Why scroll to page at index is removed?

### ISSUE THREAD

**Issue by khoren93** [maxep/MXSegmentedPager#40]
Before update to v2.0 i used this method in MXSegmentedPager
- (void) scrollToPageAtIndex:(NSInteger)index animated:(BOOL)animated;

Thanks.

**Comment by maxep** [comment]
I removed it because your can use the method `- (void) showPageAtIndex:(NSInteger)index animated:(BOOL)animated;` from MXPagerView directly.
