### ISSUE TITLE
Crashing app everytime.

### ISSUE THREAD

**Issue by classified** [maxep/MXSegmentedPager#41]
I'm trying to setup view pager. i returning 4 pages at number method , same title for every page and same tableview for every page.

P.S : I'm not using storyboards.

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* setObjectForKey: object cannot be nil (key: 0)'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010800cf65 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000109971deb objc_exception_throw + 48
    2   CoreFoundation                      0x0000000107f0ad72 -[__NSDictionaryM setObject:forKey:] + 1042
    3   MXSegmentedPager                    0x0000000108e176d1 __31-[MXPagerView loadPageAtIndex:]_block_invoke + 657
    4   MXSegmentedPager                    0x0000000108e173c3 -[MXPagerView loadPageAtIndex:] + 131
    5   MXSegmentedPager                    0x0000000108e1602c -[MXPagerView reloadData] + 876
    6   MXSegmentedPager                    0x0000000108e19a03 -[MXSegmentedPager reloadData] + 1299
    7   MXSegmentedPager                    0x0000000108e1876f -[MXSegmentedPager layoutSubviews] + 63
    8   UIKit                               0x0000000109e8911c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 710
    9   QuartzCore                          0x000000010912b36a -[CALayer layoutSublayers] + 146
    10  QuartzCore                          0x000000010911fbd0 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
    11  QuartzCore                          0x000000010911fa4e _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
    12  QuartzCore                          0x00000001091141d5 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
    13  QuartzCore                          0x00000001091419f0 _ZN2CA11Transaction6commitEv + 508
    14  QuartzCore                          0x0000000109142154 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
    15  CoreFoundation                      0x0000000107f389d7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION** + 23
    16  CoreFoundation                      0x0000000107f38947 __CFRunLoopDoObservers + 391
    17  CoreFoundation                      0x0000000107f2e59b __CFRunLoopRun + 1147
    18  CoreFoundation                      0x0000000107f2de98 CFRunLoopRunSpecific + 488
    19  GraphicsServices                    0x000000010d898ad2 GSEventRunModal + 161
    20  UIKit                               0x0000000109dd8676 UIApplicationMain + 171
    21  FoodKlik                            0x00000001068766df main + 111
    22  libdyld.dylib                       0x000000010b3af92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by maxep** [comment]
First, you shouldnt use the same view for every pages, the pager do not copy views.
The crash says that you didnt provide a page for index 0; How do you implement the data source ?

**Comment by classified** [comment]
Okay. this crash is fixed. but i have question if i am getting dynamic size array from json. My pager depends on that json array how will i handle it? as you're saying pager do not copy views.

**Comment by maxep** [comment]
Not sure what you are trying to do. But you should create and save a new table view for each page and associate them to your data model.

**Comment by classified** [comment]
Ah, one more bug found.

I pushed my MXViewPager controller to screen initialized it with 4 temp data. I did call to server after successfully getting data i assigned those data to view pagers source and try to reload them but view pager doesn't re update.

**Comment by maxep** [comment]
I'm not sure if this is a bug or an issue in your code. Do you have a sample code that reproduce the issue?
