### ISSUE TITLE
Use your VGParallaxHeader fork instead of master?

### ISSUE THREAD

**Issue by cerupcat** [maxep/MXSegmentedPager#43]
Based on the issue here: https://github.com/stoprocent/VGParallaxHeader/issues/29 is there a chance you can update to using your fork of VGParallaxHeader so that updating the header height works correctly? If not, I'll have to fork MXSegmentedPager and use your fork of VGParallaxHeader in order to fix the issues I'm seeing.

**Comment by maxep** [comment]
Hi @cerupcat,

Yes I will do that. I'm also working on a [MXParallaxHeader](https://github.com/maxep/MXParallaxHeader), but it's ready yet!
