### ISSUE TITLE
[change ParallaxHeader size]

### ISSUE THREAD

**Issue by hoangtuanfithou** [maxep/MXSegmentedPager#44]
Hello,
- can we change the height of the ParallaxHeader
- we did like this :
- first :
      segmentedPager.setParallaxHeaderView(headerView, mode: .TopFill,
          height: 300) 
- then :
      segmentedPager.setParallaxHeaderView(headerView, mode: .TopFill,
          height: 600) 
- But it is not work, Error:

``` javascript
Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x21dc73fb0 V:[PrcmQA.NewUserInfoView:0x21dbebe80(300)]>",
    "<NSLayoutConstraint:0x24863bfb0 V:[PrcmQA.NewUserInfoView:0x21dbebe80(>=600)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x24863bfb0 V:[PrcmQA.NewUserInfoView:0x21dbebe80(>=600)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

Thanks for your advice.

**Comment by maxep** [comment]
hi @hoangtuanfithou 

The method `updateParallaxHeaderViewHeight:` in VGParallaxHeader allows you to update the header height.

**Comment by hoangtuanfithou** [comment]
@maxep: Thanks so much. I will try now.

**Comment by hoangtuanfithou** [comment]
Hi @maxep,
This is the result, maybe I used the wrong way :
- the parallax header size change.
- but its header inside is not change (I tried auto-layout, also).

<img width="1438" alt="screen shot 2015-11-06 at 6 50 10 pm" src="https://cloud.githubusercontent.com/assets/93890/10996432/5199c3ba-84b7-11e5-8f7d-80d4dc14aac4.png">

**Comment by maxep** [comment]
You don't need to set your headerView's frame, VGParallaxHeader will do it for you. This might be your issue.

**Comment by hoangtuanfithou** [comment]
Thanks @maxep 
I tried again with MXSegmentPager Sample. (used updateParallaxHeaderViewHeight: of MXSegmentedPager)
But the result :
![screen shot 2015-11-07 at 1 12 30 am](https://cloud.githubusercontent.com/assets/93890/11004744/af315aa8-84ec-11e5-814e-c58b18402b09.jpg)

**Comment by maxep** [comment]
Hi @hoangtuanfithou 

This might be due to a recent merge in my local VGParallaxHeader..
I've been working on a [MXParallaxHeader](https://github.com/maxep/MXParallaxHeader) which allows you to dynamically change the header view/height/mode. It has been integrated on this [branch](https://github.com/maxep/MXSegmentedPager/tree/MXParallaxHeader), maybe you can try it!

**Comment by hoangtuanfithou** [comment]
@maxep Thank you, I am trying the branch you gave.

**Comment by hoangtuanfithou** [comment]
@maxep : 
I do the quick check, It works.
Thank you so much. It is great that you support so quickly like that.

PS: And maybe it it change height with animation options is nice.
Maybe it not need.

![e2ec130071994e497456407fe7abe6b8](https://cloud.githubusercontent.com/assets/93890/11083632/4d15688e-8864-11e5-8462-911235affb20.gif)

**Comment by hoangtuanfithou** [comment]
@maxep :
Dear Maxep
I found another thing that can be improve :
- segmentedPager.parallaxHeader.mode = .Fill;
- When user scroll the Header Up, then we call expand like :         segmentedPager.parallaxHeader.height = 600
  -> then the height doest not change, it stay the same.

Thanks so much.

**Comment by maxep** [comment]
Hi @hoangtuanfithou 

I can't reproduce your issue, when I scroll up and change the height, the content inset is changed correctly. Be aware that the header's height affects the content inset and not the content offset.

I'm not planning to add an animated height setter, but contributions are welcome ;)

**Comment by hoangtuanfithou** [comment]
@maxep : I will reproduce on sample for more detail later. Then confirm again. On my app It is still happen
about animation, It is minor, I integrate height change and see no animation is no big problem.
Nice to talk with you :beers:

**Comment by ingscjoshua** [comment]
Hello im need integrate with UICollectionView no have problem's?

**Comment by maxep** [comment]
[MXParallaxHeader](https://github.com/maxep/MXParallaxHeader) has been integrated in the new release 3.0.0

@ingscjoshua , yes it should works!
