### ISSUE TITLE
UIScrollView issue

### ISSUE THREAD

**Issue by nrdgroove** [maxep/MXSegmentedPager#5]
Hi, i implement this cool library in my app. I implement with a UIScrollView but i have this issue. Can you help me?

Thanks!

![example](https://cloud.githubusercontent.com/assets/5541569/7573811/89b0e722-f7f6-11e4-9bc6-848624e6ba12.gif)

**Comment by maxep** [comment]
Hi!

Wow thats really weird... Are you using the parallax category or you just add the pager to a scroll view?
make sure you use float value for any position, size, frame, etc... using integer may round values sometime. But I would say I've never see something like that! could you provide a sample code that reproduce the problem ?

**Comment by nrdgroove** [comment]
https://github.com/malakiya/testParallax in this url you'll find a demo

**Comment by maxep** [comment]
Hello!
This seem to be a problem from the VGParallaxHeaderMode that you use. The YTPlayerView do not support parallax effect so you shouldn't use a Fill mode. By using the Top or Center mode, the problem disappear.

Regards,
Maxime
