### ISSUE TITLE
Offset when using with UINavigationController

### ISSUE THREAD

**Issue by Elipasousa** [maxep/MXSegmentedPager#52]
Hi, I'm using MXSegmentedPager inside an UINavigationController. In iOS 8 it works great but in iOS 9 there's a blank offset of 64 at the top, which I think is 20 from the status bar and 44 from the navigation bar. The parallax header wouldn't scroll above that blank space but the segmented controller would.

I was able to fix this bug by adding this lines at the top of your function in MXParallaxHeader.m file:

``` c
- (void) setScrollViewContentTopInset:(CGFloat)top {

   if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"9.0")) {
        top = self.height;
    }
   //rest of the code
}
```

**Comment by maxep** [comment]
Hi @Elipasousa 

By doing this you ignore the previous value of the contentInset.
Have you tried to set your controller's property `automaticallyAdjustsScrollViewInsets` to `NO`?

**Comment by Elipasousa** [comment]
@maxep I know but, in my case, the solution works great for what I need. I did try that but it didn't solve the problem. I put a breakpoint at the beginning of the function and it was being called with 2 values differing from each other by 64. This only happens if the segmented pager is in a navigation controller and running on iOS9. I can provide screenshots if you want.

**Comment by maxep** [comment]
Code example will tell more than screenshots ;) 
I've just made a test example with a navigation controller targeting iOS9 and I'm able to remove the unwanted contentinset just by unchecking "Adjust Scroll View Insets" in storyboard.
[Test.zip](https://github.com/maxep/MXSegmentedPager/files/59548/Test.zip)

**Comment by Elipasousa** [comment]
I forgot to mention that I'm also using a UITabBarController. You should reproduce my problem like this: put MXSegmentedPager inside a view controller which is one of the children of tab bar controller. The tab bar is inside a navigation controller. The "Adjust Scroll View Insets" property does nothing in this case. I made a very quick demo test with the problem. 
[test.zip](https://github.com/maxep/MXSegmentedPager/files/59590/test.zip)

**Comment by maxep** [comment]
Oh ok! then you should uncheck the "Adjust Scroll View Insets" from your UITabBarController.

**Comment by Elipasousa** [comment]
@maxep  thanks a lot for your help, that solved the problem!!

**Comment by inPhilly** [comment]
What if we need to set automaticallyAdjustsScrollViewInsets to yes - is there any way to have this adjust the scrollview insets for any pagerview whose view is a scrollview?
