### ISSUE TITLE
viewWill/DidAppear and viewWill/DidDisappear aren't called

### ISSUE THREAD

**Issue by bigluck** [maxep/MXSegmentedPager#53]
Hi @maxep 

I have two `ViewControllers` loaded by `MXSegmentedPage`; in all this two `ViewControllers` can be played a video flow by the user.

When user change the current tab I have to pause the played video for the hidden tab.

I've thinked to put my logic into the `ViewController` waiting for a `viewWillAppear`/`viewDidAppear` call for the current selected tab and a `viewWillDisappear`/`viewDidDisappear` for the previous selected tab, but this methods aren't called right now.

Can you help me?

Thanks

**Comment by maxep** [comment]
Hi @bigluck 

It wont work this way, methods `view*Appear` wont get called because view controllers are inside a container. To do so, I would suggest you to use the `MXSegmentedPagerDelegate`.

**Comment by bigluck** [comment]
Ok, thanks @maxep

**Comment by hardikamal** [comment]
hi @bigluck can u plz tell me how you solved this...??? even i have to reload the viewcontroller when it appear...Thanks

**Comment by bigluck** [comment]
Yep, right now I've writted a basic dictionary of weak references for all `ViewController` instanciated by `MXPageSegue`.

``` Swift

class Weak<T: AnyObject> {
    weak var value : T?
    init (value: T) {
        self.value = value
    }
}
```

``` Swift
    private var cachedVC = [Int: Weak<UIViewController>]()
    private var cachedSelectedPageIndex = -1 {
        didSet {
            if oldValue == self.cachedSelectedPageIndex || self.cachedSelectedPageIndex == -1 {
                return
            }
            if let hiddenVC = self.cachedVC[oldValue]?.value {
                hiddenVC.viewWillDisappear(true)
                hiddenVC.viewDidDisappear(true)
            }
            if let visibleVC = self.cachedVC[self.cachedSelectedPageIndex]?.value {
                visibleVC.viewWillAppear(true)
                visibleVC.viewDidAppear(true)
            }
        }
    }
```

And finally:

``` Swift
    override func segmentedPager(segmentedPager: MXSegmentedPager, didSelectViewWithIndex index: Int) {
        self.cachedSelectedPageIndex = index
    }

    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if let mxSegue = segue as? MXPageSegue {
            self.cachedVC[mxSegue.pageIndex] = Weak(value: segue.destinationViewController)
        }
```

I know, It's not perfect, but works... :hamster:

**Comment by maxep** [comment]
Caching the view controllers would be the solution. Instead of doing it in `prepareForSegue`, You can override the data source method like this : 

``` swift
override func segmentedPager(segmentedPager: MXSegmentedPager, viewControllerForPageAtIndex index: Int) -> UIViewController {
        let vc = super.segmentedPager(segmentedPager, viewControllerForPageAtIndex: index);

        // cache VC..

        return vc;
    }
```

**Comment by hardikamal** [comment]
@maxep @bigluck The currently selected view's "viewDidAppear" is not called if we come back from other viewController. How can this be solved?
