### ISSUE TITLE
Display another view(Navigation View) after certain scroll height 

### ISSUE THREAD

**Issue by godara** [maxep/MXSegmentedPager#54]
I want to display another view when the parallaxHeader has reached its minimum height. How do I catch the event of reaching the minimum height in MXSegmentedPager?

**Comment by maxep** [comment]
Hi @godara 

For now, you can use the `progress` property of the MXParallaxHeader when the delegate method `segmentedPager:didScrollWithParallaxHeader:` is called.

**Comment by godara** [comment]
Hi @maxep 

Can you please let me know exactly where to find this method? I am referring the swift version of this project and can't find `didScrollWithParallaxHeader:` method in the workspace.

**Comment by maxep** [comment]
It's a new method, you can find it in [MXSegmentedPagerDelegate](http://cocoadocs.org/docsets/MXSegmentedPager/3.0.1/Protocols/MXSegmentedPagerDelegate.html) of the v3.0.1.

**Comment by godara** [comment]
Got the method, but in my implementation, `MXScroll` is not accessible in `MXParallaxHeader`, although it is accessible in the debug object. How do I get the `MXScroll` object from `MXParallaxHeader`?

**Comment by maxep** [comment]
No the scroll view is not yet accessible, but the MXParallaxHeader's `progress` property gives you an information on the scroll progression.

**Comment by godara** [comment]
Got it, thanks! I tried implementing it in the sample swift project you provided and it worked fine. But when I try to do this in my swift project, then only objective-c pods are installed and I can't see any swift `MXSegmentedPagerController`. Hence am not able to implement it. Should I use bridge for this? 
I can't see any bridge file in your sample swift project though.

**Comment by maxep** [comment]
How your podfile looks like ? does it contains `use_frameworks!` ? cocoapods takes care of the bridge.

**Comment by godara** [comment]
Here is the code used for Pod file:

` target 'testApp' do
pod 'TPKeyboardAvoiding', '~> 1.2.3'
pod 'MXSegmentedPager'

use_frameworks!
end `

**Comment by maxep** [comment]
Did you properly import the framework then ? `import MXSegmentedPager`
If it works in my example, then it should be an issue in your test..

**Comment by godara** [comment]
Yup I have imported the framework correctly. Can you please see this video in the link to know what issue I am facing exactly? and then let me know where am I getting wrong?
http://sendvid.com/rmb9wacj

**Comment by godara** [comment]
Also, in your project I see some `Development Pods` folder inside the `Pods` project. Are these auto-generated? as they are not generated in my project.

**Comment by maxep** [comment]
I cant tell by watching your video. I would advice you to restart from scratch. Use the last cocoapods version, set you podfile with:

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'TPKeyboardAvoiding', '~> 1.2.3'
pod 'MXSegmentedPager', '~> 3.0.2'
```

install pods and build your pod framework, then try to import and use the class.

**Comment by godara** [comment]
Hi @maxep , Thanks for your help. I recreated the pod file and restarted XCode, it works fine now. Thanks a ton!

**Comment by hoangtuanfithou** [comment]
@maxep I want to ask :+1: 
    func segmentedPager(segmentedPager: MXSegmentedPager, didScrollWithParallaxHeader parallaxHeader: MXParallaxHeader) {
        printLog(parallaxHeader.progress)
}

I see the log parallaxHeader.progress : how to handle to make a pullToRefresh
-> progress difference when HEADER height is CHANGE :(((
