### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by bigluck** [maxep/MXSegmentedPager#56]
Hi @maxep
in this last two days I'm fighting with some memory leaks in my application, but I think this leaks depends by `MXSegmentedPager`.

So I've downloaded the `MXSegmentedPager-Swift` sample and I've added a new `NavigationController` with a button in the `NavigationBar`; this button will push your `MXViewController`.

![schermata 2015-12-16 alle 12 19 10](https://cloud.githubusercontent.com/assets/1511095/11839591/3e905886-a3ef-11e5-82bd-35bd1763e9f3.png)
- I've started the application with the `Profile > Allocations` inspector and before start I've checked the "Record reference counts" option; here the `Inspector` after launching the application (it's cleaned):

![schermata 2015-12-16 alle 12 20 59](https://cloud.githubusercontent.com/assets/1511095/11839623/90a81488-a3ef-11e5-9e9e-59f0b6f1564e.png)
- I've clicked on the "Button" button; this button will push your `MXViewController` in the Navigation Controller:

![schermata 2015-12-16 alle 12 21 05](https://cloud.githubusercontent.com/assets/1511095/11839640/ad8ffea8-a3ef-11e5-98c2-78003aa04639.png)
- I've swipped between the tree tabs:

![schermata 2015-12-16 alle 12 21 09](https://cloud.githubusercontent.com/assets/1511095/11839717/44832c18-a3f0-11e5-9703-4e22c66c10ef.png)
- A snapshot of the allocations when I come back to the `Root View Controller`:

![schermata 2015-12-16 alle 12 21 13](https://cloud.githubusercontent.com/assets/1511095/11839731/61f8a994-a3f0-11e5-9c5e-db96601b9e04.png)
- I'm again in the `Root View Controller` but this time I've opened and closed the `MXViewController` subview for 10 times.

![schermata 2015-12-16 alle 12 27 56](https://cloud.githubusercontent.com/assets/1511095/11839808/05161922-a3f1-11e5-90e4-1cf4c48569c4.png)

Can you help me?

**Comment by maxep** [comment]
Hi @bigluck 
I think a see the issue, it's from MXParallaxHeader. I will try to find a fix asap. Thanks for the report!
