### ISSUE TITLE
Add common view at bottom of MXSegmentedPagerController

### ISSUE THREAD

**Issue by godara** [maxep/MXSegmentedPager#58]
Hi

I want to add a `UIView` with a button for navigation at the bottom of `UIViewController` extended from `MXSegmentedPagerController`. I kept it in xib but that's not working.

**Comment by hardikamal** [comment]
@godara were you able to achieve this? @maxep can you plz help me achieve this??

**Comment by bhavinpankanis** [comment]
@maxep  Any inputs?.
