### ISSUE TITLE
showPageAtIndex() immediately after reloadData() doesn't work

### ISSUE THREAD

**Issue by bigluck** [maxep/MXSegmentedPager#59]
Yep, I known @maxep ... I'm really sorry, again.

I'm fighting with this bug when I fetch data from a remote source.
I need to reload all viewControllers and select a defined page from the `MXSegmentedPager`.

``` Swift

class MXViewController: MXSegmentedPagerController {
    private var sections = ["Web"]

    override func viewDidLoad() {
        super.viewDidLoad()
        self.segmentedPager.backgroundColor = UIColor.whiteColor()

        // Parallax Header       
        self.segmentedPager.parallaxHeader.view = MXHeaderView.instanceFromNib();
        self.segmentedPager.parallaxHeader.mode = MXParallaxHeaderMode.Fill;
        self.segmentedPager.parallaxHeader.height = 150;
        self.segmentedPager.parallaxHeader.minimumHeight = 20;

        // Segmented Control customization
        self.segmentedPager.segmentedControl.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationDown;
        self.segmentedPager.segmentedControl.backgroundColor = UIColor.whiteColor()
        self.segmentedPager.segmentedControl.titleTextAttributes = [NSForegroundColorAttributeName : UIColor.blackColor()];
        self.segmentedPager.segmentedControl.selectedTitleTextAttributes = [NSForegroundColorAttributeName : UIColor.orangeColor()]
        self.segmentedPager.segmentedControl.selectionStyle = HMSegmentedControlSelectionStyleFullWidthStripe
        self.segmentedPager.segmentedControl.selectionIndicatorColor = UIColor.orangeColor()

        let delayTime2 = dispatch_time(DISPATCH_TIME_NOW, Int64(1 * Double(NSEC_PER_SEC)))
        dispatch_after(delayTime2, dispatch_get_main_queue()) {
            self.sections = ["Table", "Web", "Text"]
            self.segmentedPager.reloadData()
            self.segmentedPager.pager.showPageAtIndex(2, animated: false)
        }
    }

    override func numberOfPagesInSegmentedPager(segmentedPager: MXSegmentedPager) -> Int {
        return self.sections.count
    }

    override func segmentedPager(segmentedPager: MXSegmentedPager, titleForSectionAtIndex index: Int) -> String {
        return self.sections[index];
    }
}
```

**Comment by khoren93** [comment]
+1

**Comment by malinka** [comment]
Have you solve it?

**Comment by maxep** [comment]
Well I couldnt reproduce with your snippet in the last [release](https://github.com/maxep/MXSegmentedPager/releases/tag/3.1.0)..

**Comment by gsoykan** [comment]
Hey ! I think the problem is still there in the newer versions. Below is my code on viewWillAppear, pretty much the same thing as this issue. And I am using custom segue names for reversing the viewControllers. The result is attached, the view is not loaded properly. If you have time could you help me with this issue @maxep  :)
```swift
       self.segmentedPager.reloadData()
        if self.mxProfilePresenter?.isLanguageEnglish() ?? true {
            self.segmentedPager.pager.showPage(at: 0, animated: false)
        } else {
            self.segmentedPager.pager.showPage(at: 2, animated: false)
        }
```
![simulator screen shot - iphone 8 - 2018-12-10 at 16 23 41](https://user-images.githubusercontent.com/11638870/49735579-9f248780-fc98-11e8-8846-f23ea47d8f15.png)

**Comment by jayaprada-behera** [comment]
It worked for me for english to arabic language app 
/*
Change Custom segue name as per   segueIdentifiers array
*/
class MXPersonalViewController: MXSegmentedPagerController {
    
    @IBOutlet var headerView: UIView!
    var segueIdentifiers = [String]()
    var headerTitle = [String]()
    
    @IBAction func backBtnTapped(_ sender: UIButton){
        self.navigationController?.popViewController(animated: true)
    }
    override func viewDidLoad() {
        super.viewDidLoad()
        
        if Language.isRightToLeft == true {
            segueIdentifiers = ["VC1","VC2","VC3"]
            headerTitle = ["VC1, "VC2", "VC3"]
            DispatchQueue.main.async {
                self.segmentedPager.segmentedControl.selectedSegmentIndex = self.segueIdentifiers.count - 1
                self.segmentedPager.pager.showPage(at: self.segueIdentifiers.count - 1, animated: false)
                self.segmentedPager.pager.reloadData()
             }
        }else{
            segueIdentifiers = ["VC3","VC2","VC1"]
            headerTitle = ["VC3", "VC2", "VC1"]
         }
        
        
         segmentedPager.parallaxHeader.view = headerView
        headerView.backgroundColor = Constants.Colors.AppThemeColor
        segmentedPager.parallaxHeader.mode = .fill
        segmentedPager.parallaxHeader.height = 30
        segmentedPager.parallaxHeader.minimumHeight = 20
        segmentedPager.backgroundColor = .white
        // Segmented Control customization
        segmentedPager.segmentedControl.selectionIndicatorLocation = .down
        segmentedPager.segmentedControl.backgroundColor =  Constants.Colors.AppThemeColor //UIColor.init(red: 5/255, green: 109/255, blue: 255/255, alpha: 1)
        segmentedPager.segmentedControl.titleTextAttributes = [NSAttributedString.Key.foregroundColor : UIColor.init(red: 248/255, green: 248/255, blue: 248/255, alpha: 1)]
        segmentedPager.segmentedControl.selectedTitleTextAttributes = [NSAttributedString.Key.foregroundColor : UIColor.white]
        segmentedPager.segmentedControl.selectionStyle = .textWidthStripe
        
        segmentedPager.segmentedControl.selectionIndicatorColor = UIColor.init(red: 244/255, green: 205/255, blue: 15/255, alpha: 1)
        segmentedPager.segmentedControl.titleTextAttributes = [NSAttributedString.Key.foregroundColor : UIColor.white]
        segmentedPager.segmentedControl.selectedTitleTextAttributes = [NSAttributedString.Key.foregroundColor : UIColor.white,NSAttributedString.Key.font: robotoRegular18]
        // Do any additional setup after loading the view.
        
    }
  
    override func segmentedPager(_ segmentedPager: MXSegmentedPager, titleForSectionAt index: Int) -> String {
        return headerTitle[index]
    }
    
    override func segmentedPager(_ segmentedPager: MXSegmentedPager, didScrollWith parallaxHeader: MXParallaxHeader) {
        print("progress \(parallaxHeader.progress)")
    }
    
    override func segmentedPager(_ segmentedPager: MXSegmentedPager, segueIdentifierForPageAt index: Int) -> String {
        return segueIdentifiers[index]
        
        
    }
    override func numberOfPages(in segmentedPager: MXSegmentedPager) -> Int {
        return segueIdentifiers.count
    }

**Comment by hyd00** [comment]
@jayaprada-behera How to know which segue identifier connects to which view controller? Have u defined that in storyboard?

**Comment by miladyalda** [comment]
Hey!

Has anyone solved it? I have the same problem now :(
