### ISSUE TITLE
Is there any way by which I can switch off the horizontal bouncing ?

### ISSUE THREAD

**Issue by egupta171** [maxep/MXSegmentedPager#62]
Content view should not bounce when user is at first or the last view controller

**Comment by maxep** [comment]
Hi @egupta171 

Currently no, sorry.. but I will add it to MXPagerView.

**Comment by gkhnaydn** [comment]
In MXSegmentedPager.m file, add _pager.bounce = NO on - (MXPagerView *)pager method. That s all

it s like:

- (MXPagerView *)pager {
    if (!_pager) {
        _pager = [[MXPagerView alloc] initWithFrame:self.frame];
        _pager.delegate = self;
        _pager.dataSource = self;
        _pager.bounces = NO;
        [self.contentView addSubview:_pager];
    }
    return _pager;
}
