### ISSUE TITLE
Right to left selection

### ISSUE THREAD

**Issue by nwios** [maxep/MXSegmentedPager#64]
Hi, Good morning 

I  have an issue with MXSegmentedPager, I want to change the selection from left to right to right to left, I did some solutions but not running right as I want, at following you will find the code that i written: 
- (void)viewDidLoad {
  [super viewDidLoad];
  // Do any additional setup after loading the view.
  __segmentedPager = [[MXSegmentedPager alloc] initWithFrame:CGRectMake(0.0f, 0.0f, self.view.frame.size.width, self.view.frame.size.height-20.0f)];
  __segmentedPager.segmentedControl.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationDown;
  __segmentedPager.segmentedControl.selectionIndicatorColor = [UIColor colorWithRed:57.0/255.0 green:114.0/255.0 blue:182.0/255.0 alpha:1.0];
  __segmentedPager.segmentedControl.selectionStyle = HMSegmentedControlSelectionStyleFullWidthStripe;
  __segmentedPager.segmentedControl.titleTextAttributes = @{NSFontAttributeName:[UIFont fontWithName:@"GESSTwoLight-Light" size:16.0]};
  __segmentedPager.segmentedControl.selectedTitleTextAttributes = @{NSForegroundColorAttributeName : [UIColor colorWithRed:57.0/255.0 green:114.0/255.0 blue:182.0/255.0 alpha:1.0]};
  __segmentedPager.pager.gutterWidth = 20;
  __segmentedPager.delegate    = self;
  __segmentedPager.dataSource  = self;
  [self.view addSubview:__segmentedPager];

}
# pragma mark - Segmented Pager Delegate
- (void)segmentedPager:(MXSegmentedPager *)segmentedPager didSelectViewWithTitle:(NSString *)title {
  NSLog(@"%@ page selected.", title);
  }
# pragma mark - Segmented Pager DataSource
- (NSInteger)numberOfPagesInSegmentedPager:(MXSegmentedPager *)segmentedPager {
  return 3;
  }
- (NSString *)segmentedPager:(MXSegmentedPager *)segmentedPager titleForSectionAtIndex:(NSInteger)index {
  return [@[@"الثلاجات",@"الغسالات",@"المكيفات"] objectAtIndex:index];
  }

-(void)segmentedPager:(MXSegmentedPager *)segmentedPager didScrollWithParallaxHeader:(MXParallaxHeader *)parallaxHeader{
    NSLog(@"SegmentedPager didScrolled.");

}
- (UIView *)segmentedPager:(MXSegmentedPager *)segmentedPager viewForPageAtIndex:(NSInteger)index {
  UIViewController *rvc;
  switch (index) {
      case 0:
      {
      rvc = [self.storyboard instantiateViewControllerWithIdentifier:@"RFEID"];
          [rvc.view setFrame:CGRectMake(0, 0, __container.frame.size.width, __container.frame.size.height)];
          [self addChildViewController:rvc];
          [__container addSubview:rvc.view];
      }
          break;
      case 1:
      {
        rvc = [self.storyboard instantiateViewControllerWithIdentifier:@"WMAID"];
          [rvc.view setFrame:CGRectMake(0, 0, __container.frame.size.width, __container.frame.size.height)];
          [self addChildViewController:rvc];
          [__container addSubview:rvc.view];
      }
          break;
      case 2:
      {
         rvc = [self.storyboard instantiateViewControllerWithIdentifier:@"ACOID"];
          [rvc.view setFrame:CGRectMake(0, 0, __container.frame.size.width, __container.frame.size.height)];
          [self addChildViewController:rvc];
          [__container addSubview:rvc.view];
      }
          break;
      default:
          break;
  }
  
  return rvc.view;
  }

**Comment by nwios** [comment]
when I use MXSegmentPager property .segmentedControl.selectedSegmentIndex = 2; "2 is last index in normal case"  with property configuration, the app working fine but when I scrolling to index 1 then the scroll go back to index 2. 

i tried many of times but all solutions not working as well. 

could you help me?

**Comment by maxep** [comment]
Hi @Doss-ry 
Im currently very busy with regular job, but I will have a look asap.

**Comment by maxep** [comment]
see #59
