### ISSUE TITLE
Redundant data in childViewControllers

### ISSUE THREAD

**Issue by mamouneyya** [maxep/MXSegmentedPager#65]
Hello,

While tracing some code in the library, I've just noticed that when you create a new view controller in `MXSegmentedPagerController's segmentedPager:viewForPageAtIndex:` method, you immediately add it to the childViewControllers of the page view controller without removing old references. As a result, if you kept going back and forth between your tabs (supposing you have 3+ tabs, so the pageViewController have the chance to destroy controllers), you'll end up with the childViewControllers array having a bunch of unused references.

**Comment by maxep** [comment]
Hi @mamouneyya 

Im currently very busy with regular job, but I will have a look asap.

**Comment by mamouneyya** [comment]
Sure man. Take your time. Good luck in your job!

**Comment by maxep** [comment]
Fixed in [3.1.0](https://github.com/maxep/MXSegmentedPager/releases/tag/3.1.0)
