### ISSUE TITLE
Pin view above HMSegmentedControl ?

### ISSUE THREAD

**Issue by MadeByDouglas** [maxep/MXSegmentedPager#68]
So I am using this module to try and recreate Twitter's profile page. One thing I am unsure how to do is get content above the HMSegmentedControl but is still pinned to it so it scrolls out of the way. When i add subviews to the parallax header view (in the xib file) they are totally static and dont move with the HMSegmentedControl menu.

Any ideas how I would tweak it? I dove into the MXSegmentedPager.m file but to no avail.

**Comment by maxep** [comment]
Hi @Audentia 
To mimic the twitter profile page you should set the parallax header's mode to `MXParallaxHeaderModeFill` and the `minimumHeight'. Then you have to play with your header view's constraints. Check the [MXParallaxHeader](https://github.com/maxep/MXParallaxHeader) examples.

**Comment by MadeByDouglas** [comment]
ah hah!

Yes I was having the content i wanted pinned constrained to superview when i should have just constrained it to the background imageview. Also i had things in a subview which was constrained to the superview which kept things static.

Simple, thank you! 

Question: Now that I’ve taken a closer look at the examples, why do you set background image bottom constraint on the nib to -35 for the two rockets but not the Falcon?

**Comment by maxep** [comment]
You can ignore the -35, I just wanted to add an icon on the bottom of the headers but I never did :)

**Comment by MadeByDouglas** [comment]
Ah ok gotcha :)
Thanks again! Great module
