### ISSUE TITLE
child view controller access the parent

### ISSUE THREAD

**Issue by MadeByDouglas** [maxep/MXSegmentedPager#70]
hows does the child controller see the parent VC / the MXPager? in the child when i type `self.parentViewController` it comes up nil

I have a child tableViewController that needs to hit the navController which the parent MXPager has so it presents via show not modal.

I set it up programmatically with my own super class and use your delegates `MXSegmentedPagerDelegate, MXSegmentedPagerDataSource`

And perhaps connected, right now I'm using `viewForPageAtIndex` but as I have custom controllers it seems I'd rather use `viewControllerForPageAtIndex` but that only seems available when i subclass MXPager..?

```
    func segmentedPager(segmentedPager: MXSegmentedPager, viewForPageAtIndex index: Int) -> UIView {
        return viewsArray[index] as! UIView
    }

    func segmentedPager(segmentedPager: MXSegmentedPager, viewControllerForPageAtIndex index: Int) -> UIViewController {
        return controllersArray[index] as! UIViewController
    }
```

**Comment by maxep** [comment]
Hi @Audentia 

In your `viewForPageAtIndex` method, you need to add your VC as a child by using the [`addChildViewController`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/#//apple_ref/occ/instm/UIViewController/addChildViewController:) and then return the VC's view. Have a look at the [MXSegmentedPagerController.m](https://github.com/maxep/MXSegmentedPager/blob/master/MXSegmentedPager/MXSegmentedPagerController.m).

**Comment by MadeByDouglas** [comment]
ahh ok, i thought that was handled automagically, makes sense. Now, so whats the difference between viewForPage and viewControllerForPage ? in the example viewController seems to be for storyboard, is that it?

**Comment by maxep** [comment]
Hi @Audentia , sorry for the late response..
MXSegmentedPager only manage view as page. If you want to manage VC, I suggest you to use MXSegmentedPagerController which overload the data source protocol by adding the `viewControllerForPage` method. Its also manage storyboard automatically.

**Comment by MadeByDouglas** [comment]
So i would have to subclass MXSegmentedPagerController then? Or am i missing something? I dont see a MXSegmentedPagerControllerDelegate for example. Thanks btw, i appreciate you helping me out.

**Comment by MadeByDouglas** [comment]
subclassing worked i'll go ahead and close this
