### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by hoangtuanfithou** [maxep/MXSegmentedPager#72]
Dear @maxep Can you make the project compatible with Carthage ?
I really love to use the control in our Swift project.

**Comment by maxep** [comment]
Hi @hoangtuanfithou 
Yes it's on the roadmap!

**Comment by hoangtuanfithou** [comment]
@maxep Thanks so much :+1: .
I will wait

**Comment by hoangtuanfithou** [comment]
👍
