### ISSUE TITLE
Segmented pager going above Parallax header button

### ISSUE THREAD

**Issue by rahulvyas** [maxep/MXSegmentedPager#73]
HI There,

First of all thanks for the amazing control.
I am stuck at this point.
I have created a parallax header and I've added a subview at the bottom. Now when I scroll to top the segmented pager goes above the subview. How do I prevent this ?
See screenshot
![screen shot 2016-03-09 at 3 18 46 pm](https://cloud.githubusercontent.com/assets/87060/13632031/c0043dd2-e60d-11e5-8a20-627654f1fd78.png)
![screen shot 2016-03-09 at 3 18 55 pm](https://cloud.githubusercontent.com/assets/87060/13632032/c0073a14-e60d-11e5-9d6f-002a9280ba90.png)

**Comment by maxep** [comment]
Hi @rahulvyas 
How do you layout your header subview, do you use constraints?

**Comment by rahulvyas** [comment]
Yes I have copied the xib from sample and added the subview at bottom. Subview as vertical spacing from imageview. I'll upload the constraints screenshots

**Comment by rahulvyas** [comment]
Also my app crashesh when i update to the new version of segment pager and parallax header

**Comment by rahulvyas** [comment]
Here is the screenshot of constraints.
![screen shot 2016-03-11 at 11 57 52 am](https://cloud.githubusercontent.com/assets/87060/13694992/a259e54c-e780-11e5-8993-10d7a1c2e3c7.png)

Also tell me how can I add buttons on top of header. I want something like badoo app does in it's parallax header. It blurs the header and then button appears animated on side. If you got time then have a look at badoo iOS app.

**Comment by maxep** [comment]
It's probably a constraint problem, but I cant tell with your screenshot, could you provide a sample code that reproduce your issue.
For your blur and button animation, you can use the MXParallaxHeader protocol, see the falcon header example.

**Comment by rahulvyas** [comment]
I think the issue is due to translucent navigation bar. can you verify this in sample project ? May be constraints need to be updated.
