### ISSUE TITLE
Horizontal Scrolling.

### ISSUE THREAD

**Issue by dkeso611** [maxep/MXSegmentedPager#75]
Anyway to turn off horizontal scrolling? I tried setting userDragging to NO, locking the horizontal pan, commenting out your gesture recognizer, nothings seems to be working. My app has use of left and right swiping, and its lost that functionality. It worked prior updating your pod.

**Comment by maxep** [comment]
Have you tried `self.segmentedPager.pager.scrollEnabled = NO`?

**Comment by dkeso611** [comment]
That works! Thanks! much appreciated.
