### ISSUE TITLE
Add blurred segmented control to the bottom of parallax header image

### ISSUE THREAD

**Issue by WorldNull** [maxep/MXSegmentedPager#76]
Hi Max, 

Could you tell me how to place the segmented control at the bottom of the parallax header image? And as you can see in the following image, the segmented control is also blurred. I've been trying for several hours... Thanks!

![image](https://cloud.githubusercontent.com/assets/16506360/14070005/fd578936-f46e-11e5-9341-bdf457c822c7.png)

**Comment by maxep** [comment]
Hi @WorldNull 

Sorry but the current design wont let you have the header behind the segmented control. You will have to rework it..

**Comment by WorldNull** [comment]
@maxep 

Ok. Is there is a way to implement a blur effect on top of the stretchy header?
