### ISSUE TITLE
Is it possible to load UIViewController's into the segmentedcontroller's views?

### ISSUE THREAD

**Issue by juliusbtesh** [maxep/MXSegmentedPager#79]
Title says it all.

Thanks!

**Comment by maxep** [comment]
[MXSegmentedPagerControllerDataSource](https://github.com/maxep/MXSegmentedPager/blob/master/MXSegmentedPager/MXSegmentedPagerController.h) says it all!

**Comment by juliusbtesh** [comment]
Hmm, Im not sure if I can use this method. I'm using a UIViewController with a property of a segmentedPager this way I can position it in the place I need it on the screen along with using a navigation bar on top. So I don't think I can subclass the segmentedPagerController.

**Comment by maxep** [comment]
The solution would be to add controllers as childViewController and return the UIViewController.view to the `MXSegmentedPagerDataSource`. You can have a look at the [MXSegmentedPagerController.m](https://github.com/maxep/MXSegmentedPager/blob/master/MXSegmentedPager/MXSegmentedPagerController.m).

**Comment by juliusbtesh** [comment]
Sweet, Thanks I was having some issues but will run more tests.
