### ISSUE TITLE
Lazy load each page.

### ISSUE THREAD

**Issue by cerupcat** [maxep/MXSegmentedPager#8]
I'm wondering if it'd be easy to add the ability to lazily load a page. For example, rather than allocating all views for each tab on creation, I'd probably want to only load the current one in view or the current one and the next one so that I don't keep them all in memory. Essentially having something more like UIPageViewController where the pages are reused or allocated/deallocated when shown / hidden would be ideal.

Any thoughts on how this might be accomplished?

**Comment by maxep** [comment]
Yes I thought about this as well, this is probably the next evolution. I don't know how yet..
Contribution are more than welcome ;)

**Comment by cerupcat** [comment]
Yeah, I just wanted to check if you had already been thinking about it or not. If I get a chance, i'll see if it's something I can add after getting a little more familiar with the latest code. :)

**Comment by maxep** [comment]
@cerupcat ,

I have made several changes to support this feature. All the load and unload pages process is handle by the MXPagerView (which replace the container). Depending on the transition style, it will load the current page and neighbors and unload others page.
It also supports class and nib registration for reusable pages.
