### ISSUE TITLE
Odd Scrolling Behavior

### ISSUE THREAD

**Issue by rjmiller2543** [maxep/MXSegmentedPager#85]
I'm getting this strange behavior whenever I try to switch the pager to the second screen.  I have three pages, and if I try to swipe to page two, the indicator shows it's on page two, but the page being shown is still page one, and the same is true if I go from three to two.  If I scroll a second time, it goes to the correct page.  Here's an example of it below:
![mxpagererrorgif](https://cloud.githubusercontent.com/assets/6697684/15227958/9565b11a-1857-11e6-84eb-da0e89ea33f3.gif)

I have the same pager implemented on another view controller without any issues.. 

Any help is greatly appreciated, and please let me know if there's anything I can do..

**Comment by maxep** [comment]
Hi @rjmiller2543 

This is due to an issue in [MXPagerView](https://github.com/maxep/MXPagerView). It as been fixed but not released yet, you can try the latest code.
