### ISSUE TITLE
Show page at index not working with storyboard

### ISSUE THREAD

**Issue by dkeso611** [maxep/MXSegmentedPager#86]
Thanks for your Pager. I have three pages. When the app loads, i would like to show the page at index 1 under a certain condition. I use `showPageAtIndex`. The segmented control goes to the correct index but the page is incorrect.
i also use `- (NSString *)segmentedPager:(MXSegmentedPager *)segmentedPager segueIdentifierForPageAtIndex:(NSInteger)index {
` and i return the segue identifiers. Thanks again!

**Comment by MadeByDouglas** [comment]
I am wanting to do the same thing. I tried 
`self.segmentedPager.segmentedControl.selectedSegmentIndex = 1`
and similarly the control goes to right index but the page which is loaded is not correct.

Out of curiosity, where is the `showPageAtIndex` method? i could not find it

**Comment by dkeso611** [comment]
'[self.segmentedPager.pager showPageAtIndex:1 animated:NO]'

**Comment by dkeso611** [comment]
`[self.segmentedPager.pager showPageAtIndex:1 animated:NO]`

**Comment by MadeByDouglas** [comment]
ah right, there it is. Ok so I called `[self.segmentedPager.pager showPageAtIndex:1 animated:NO]` in viewDidAppear and it is moving both the segmented control and the page properly. It does not work in viewWillAppear or earlier (aka viewDidLoad) in the controller's load cycle it seems. Where do you call it?

**Comment by dkeso611** [comment]
I call it in viewDidLoad. Are you using storyboards?

**Comment by MadeByDouglas** [comment]
no storyboards for me. Oh wow i flipped the methods on that last message. (I will edit it so its fixed now) it works in viewDidAppear, it does NOT work in viewDidLoad or viewWillAppear. I believe the controllers are not properly instantiated until after viewWillAppear completely finishes, so it cannot change them properly there.

**Comment by dkeso611** [comment]
Thanks!! I put it in viewDidAppear and it works. Only issue is that viewDidAppear gets called every time i navigate away and back to the pager. I set a bool in the viewDidLoad, so `showPageAtIndex` is only called once. This fixes my situation specifically. 
Thanks again!

**Comment by MadeByDouglas** [comment]
for sure!

**Comment by 3r1k83** [comment]
I have three tab segnetpager. I use storyboard in obj-c. I have strange behavior, when I go from tab 1 to 2 the third controller is loaded. When I go from 3 to 2, first controller is loaded. This can be ok in my case, but when I go from 2 to 1 or 2 to 3 no controller is loaded. I want to load controller when I press be tab (for ex. I press the 1 and the 1 is loaded).
I hope I explained myself :)
Do I do something wrong? How is correct implementation?
