### ISSUE TITLE
TableView rows disappearing 

### ISSUE THREAD

**Issue by vjujjavarapu-zz** [maxep/MXSegmentedPager#89]
Scrolling too fast will clear the tableview rows ( fetching data from remote server)  

Is there any way that we can cache the tableview because if i switch between the segments the data fetched disappears. Retaining data or maintaining the selected segment helps.

**Comment by vjujjavarapu-zz** [comment]
Its not your issue i fixed it.

**Comment by hardikamal** [comment]
@vjujjavarapu Even I am facing the same issue when clicking on tabs too fast the rows disappear. How did you solve this?
