### ISSUE TITLE
images with clipsToBounds getting undone when paged off screen.

### ISSUE THREAD

**Issue by MadeByDouglas** [maxep/MXSegmentedPager#90]
So I have several pages in the MXSegmentedPager all with many images loaded in cells in tableViewControllers. When they first load, clipsToBounds is properly enabled and things look fine. As soon though as a page is past the one immediately left or right of the visible one, it seems this is set to false and I can't figure out how to turn it back on at the cell level. The cells don't need to be reconfigured so they never call their configure UI methods. Is there a method that shows when a page in the pageController has just become visible, like viewWillAppear or something similar?

**Comment by maxep** [comment]
Hi, I'm not sure to understand your issue. As it hasnt been followed for a while, I will close it.
Please dont hesitate to reopen if you are still struggling.
