### ISSUE TITLE
Disable scrolling on a specific View Controller. 

### ISSUE THREAD

**Issue by vjujjavarapu-zz** [maxep/MXSegmentedPager#91]
Is it possible , if i select one segment i can programatically disable scroll on that specific view controller. and when i switch segments . i can get the scrolling back. ?

**Comment by maxep** [comment]
You can use `self.segmentedPager.pager.scrollEnabled = NO;`
rf. #30

**Comment by vjujjavarapu-zz** [comment]
This will disable scrolling across all the 4 view controllers i have. I want to disable scroll only on the last segment which shows the 4th view controller.

**Comment by maxep** [comment]
You can try implementing the delegate method like this : 

``` objective-c
- (void)segmentedPager:(MXSegmentedPager*)segmentedPager didSelectViewWithIndex:(NSInteger)index {
   segmentedPager.pager.scrollEnabled = (index != 4);
}
```

**Comment by vjujjavarapu-zz** [comment]
This is not working.
