### ISSUE TITLE
Could not fetch ChildViewController instance 

### ISSUE THREAD

**Issue by SSGangwar** [maxep/MXSegmentedPager#92]
I am using MXSegmentedPager and add controllers with the help of segue from storyboard as in Swift Example. Now when i receive data from server, i want to reload all controllers values.
I tried to fetch instance of ViewControllers, so that i could pass values to controller, but could not find a way to fetch instance of current view controllers.
Please let me know, how can i find instance of controllers.
Thanks

**Comment by maxep** [comment]
Hi @SSGangwar 

You will need to subclass `MXSegmentedPagerController` and override : 

``` swift
override func segmentedPager(segmentedPager: MXSegmentedPager, viewControllerForPageAtIndex index: Int) -> UIViewController {
        let vc = super.segmentedPager(segmentedPager, viewControllerForPageAtIndex: index)

        // pass value to vc

        return vc
    }
```

**Comment by luongnhatlam** [comment]
@maxep hello, I have a question, I have many type of ViewControllers and ViewModel, I want to pass per ViewModel for per VC. So if I do follow your way, is it good???
