### ISSUE TITLE
Custom height SegmentedControl(HMSegmentedControl) within the MXSegmentedPageR?

### ISSUE THREAD

**Issue by vjujjavarapu-zz** [maxep/MXSegmentedPager#95]
can you change the height of the segmented control ?

**Comment by maxep** [comment]
See delegate method [`heightForSegmentedControlInSegmentedPager:`](http://cocoadocs.org/docsets/MXSegmentedPager/3.0.5/Protocols/MXSegmentedPagerDelegate.html#//api/name/heightForSegmentedControlInSegmentedPager:).
