### ISSUE TITLE
Disable scrolling on a certain segment. 

### ISSUE THREAD

**Issue by vjujjavarapu-zz** [maxep/MXSegmentedPager#96]
self.segmentedPager.pager.scrollEnabled = false doesn't work in Swift.

**Comment by vjujjavarapu-zz** [comment]
override func segmentedPager(segmentedPager: MXSegmentedPager, didSelectViewWithIndex index: Int) {
        if index == 3 {
            segmentedPager.pager.scrollEnabled = false 
        }
    }

**Comment by vjujjavarapu-zz** [comment]
@maxep  please respond

**Comment by maxep** [comment]
If I add this : 

``` swift
override func segmentedPager(segmentedPager: MXSegmentedPager, didSelectViewWithIndex index: Int) {
        segmentedPager.pager.scrollEnabled = !(index == 1)
}
```

To `MXViewController.swift` in the swift example, its works! the scroll is disable on the second page.

**Comment by karthikwifin** [comment]
@maxep I couldn't swipe views horizontally. What I am doing by mistake? Can you please help?
